import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const reference = "7e9c8050e5b47405a4f7e5ad214375451bfa28be";
const referencePath = "apps/windows/src/styles-windows-shared-latest.css";
const outputPath = path.join(root, "src/styles-windows-shared-latest.css");

const source = execFileSync("git", ["show", `${reference}:${referencePath}`], {
  cwd: root,
  encoding: "utf8",
  maxBuffer: 8 * 1024 * 1024,
  timeout: 30_000,
});

const tree = postcss.parse(source, { from: `${reference}:${referencePath}` });

function isWindowsOfficeSelector(selector) {
  // Negative Office guards are shared desktop scoping. Positive Office
  // selectors belong to the Windows VSTO/WebView2 session surface and must
  // not replace the native macOS Office header or Apply/Cancel controls.
  const withoutSharedGuards = selector
    .replaceAll(":not(.is-office-workspace)", "")
    .replaceAll(":not(.office-dialog-shell)", "");
  return /office/i.test(withoutSharedGuards);
}

tree.walkRules((rule) => {
  const sharedSelectors = rule.selectors.filter(
    (selector) => !isWindowsOfficeSelector(selector),
  );
  if (sharedSelectors.length === 0) {
    rule.remove();
    return;
  }
  rule.selectors = sharedSelectors;
});

// Remove containers left empty after stripping Windows Office selectors.
let removedEmptyContainer = true;
while (removedEmptyContainer) {
  removedEmptyContainer = false;
  tree.walkAtRules((rule) => {
    if (rule.nodes && rule.nodes.length === 0) {
      rule.remove();
      removedEmptyContainer = true;
    }
  });
}

const referenceSha256 = createHash("sha256").update(source).digest("hex");
const generatedBody = tree.toString().trimEnd();
const generated = `/* Generated by scripts/import_windows_shared_styles.mjs.
   Source: ${reference}:${referencePath}
   Source SHA256: ${referenceSha256}
   Windows Office/VSTO/WebView2 session selectors are intentionally excluded;
   macOS keeps its native Office header, Apply/Cancel flow, OCR and AppKit shell. */

${generatedBody}
`;

writeFileSync(outputPath, generated, "utf8");

const generatedSha256 = createHash("sha256").update(generated).digest("hex");
console.log(
  JSON.stringify(
    {
      reference,
      referencePath,
      referenceSha256,
      outputPath,
      generatedSha256,
      lineCount: generated.split("\n").length - 1,
    },
    null,
    2,
  ),
);
