import { patchVisualTexMathLiveCoreCompatibility } from "./vite.mathliveCoreCompatibility";
import { patchVisualTexMathLiveEditingKernel } from "./vite.mathliveEditingKernel";
import { patchVisualTexMathLiveSelection } from "./vite.mathliveSelection";
import { patchVisualTexMathLiveSemanticCompletion } from "./vite.mathliveSemanticCompletion";

const replacementCount = (source: string, target: string) =>
  source.split(target).length - 1;

function replaceExactly(
  source: string,
  target: string,
  replacement: string,
  label: string,
) {
  const count = replacementCount(source, target);
  if (count !== 1) {
    throw new Error(`VisualTeX MathLive behavior patch ${label} anchor changed (${count}).`);
  }
  return source.replace(target, replacement);
}

/**
 * VisualTeX behavior fork for MathLive 0.109.2.
 *
 * Keep MathLive's renderer, model, font and geometry implementation intact while
 * changing only editor semantics that conflict with VisualTeX. Every patch is
 * guarded by an exact source anchor so an upstream MathLive change fails the
 * build instead of silently changing behavior.
 */
export function patchVisualTexMathLiveBehavior(source: string) {
  let patched = patchVisualTexMathLiveCoreCompatibility(source);

  patched = replaceExactly(
    patched,
    [
      '    const weight = weightString(x[0]);',
      '    if (weight !== "bold") return joinLatex(emitVariantRun(x, options));',
    ].join("\n"),
    [
      '    const weight = weightString(x[0]);',
      '    const visualTexVariant = variantString(x[0]);',
      '    // bolditalic is already serialized by emitVariantRun as \\mathbfit.',
      '    // Wrapping it in an additional \\mathbf is redundant and changes',
      '    // round-trip style semantics.',
      '    if (weight !== "bold" || visualTexVariant.endsWith("-bolditalic"))',
      '      return joinLatex(emitVariantRun(x, options));',
    ].join("\n"),
    "avoid duplicate bold wrapper around mathbfit variants",
  );

  // Normal raw-LaTeX groups are intentionally omitted from the public value
  // until MathLive completes them. A VisualTeX source wrapper is different:
  // the raw shell itself is the live formula state (for example \\mathbb{}),
  // so only tagged wrapper groups participate in LaTeX serialization.
  patched = replaceExactly(
    patched,
    '    return run.filter((x) => x instanceof LatexAtom && !x.isSuggestion).map((x) => x.value);',
    [
      '    return run',
      '      .filter((x) => (x instanceof LatexAtom && !x.isSuggestion) ||',
      '        (x instanceof LatexGroupAtom && x.visualTexSourceWrapper))',
      '      .map((x) => x instanceof LatexGroupAtom ? x._serialize(_options) : x.value);',
    ].join('\n'),
    "VisualTeX source wrapper participates in public LaTeX serialization",
  );

  // Software keyboards and Windows Unicode input may supply a key without a
  // physical code. Control keys have no printable keyboard-layout mapping.
  patched = replaceExactly(patched,
    '  const mapping = Object.entries(getActiveKeyboardLayout().mapping);\n  let altKey = false;\n  let shiftKey = false;\n  let code = "";',
    [
      '  const mapping = Object.entries(getActiveKeyboardLayout().mapping);',
      '  let altKey = evt.altKey;',
      '  let shiftKey = evt.shiftKey;',
      '  const controls = ["Enter", "Tab", "Backspace", "Delete", "Escape", "ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Home", "End", "PageUp", "PageDown"];',
      '  let code = controls.includes(evt.key) ? evt.key : ({Return: "Enter", Esc: "Escape", Del: "Delete", Spacebar: "Space", " ": "Space"}[evt.key] || "");',
    ].join('\n'), "normalize control keys without physical codes");
  patched = replaceExactly(patched,
    '  return new KeyboardEvent(evt.type, __spreadProps(__spreadValues({}, evt), { altKey, shiftKey, code }));',
    '  return new KeyboardEvent(evt.type, { key: evt.key, code, altKey, shiftKey, ctrlKey: evt.ctrlKey, metaKey: evt.metaKey, repeat: evt.repeat, isComposing: evt.isComposing, location: evt.location });',
    "preserve keyboard getters when normalizing code-less events");

  patched = replaceExactly(
    patched,
    [
      '      const hostPointerHandler = (evt) => {',
      '        if (evt.target !== this.host) return;',
      '        this.handleEvent(evt);',
      '      };',
    ].join("\n"),
    [
      '      const hostPointerHandler = (evt) => {',
      '        const path = typeof evt.composedPath === "function" ? evt.composedPath() : [];',
      '        if (path.includes(this.element)) return;',
      '        if (evt.target !== this.host) return;',
      '        this.handleEvent(evt);',
      '      };',
    ].join("\n"),
    "deduplicate shadow-retargeted host pointer events",
  );

  patched = replaceExactly(
    patched,
    [
      '      case "mousedown":',
      '        if (this.userSelect !== "none" && !((_b3 = evt.target) == null ? void 0 : _b3.closest(',
      '          "[part=virtual-keyboard-toggle],[part=menu-toggle]"',
      '        )))',
      '          onPointerDown(this, evt);',
      '        break;',
    ].join("\n"),
    [
      '      case "mousedown":',
      '        // Chromium/WebView2 already dispatched pointerdown for this physical click.',
      '        // Replaying the selection on mousedown can move a selected placeholder.',
      '        if (typeof PointerEvent !== "undefined") break;',
      '        if (this.userSelect !== "none" && !((_b3 = evt.target) == null ? void 0 : _b3.closest(',
      '          "[part=virtual-keyboard-toggle],[part=menu-toggle]"',
      '        )))',
      '          onPointerDown(this, evt);',
      '        break;',
    ].join("\n"),
    "deduplicate pointerdown and mousedown selection",
  );

  patched = replaceExactly(
    patched,
    "function onPointerDown(mathfield, evt) {",
    [
      "function onPointerDown(mathfield, evt) {",
      "  const visualTexPointerSignature = [evt.type, evt.pointerId ?? 0, evt.timeStamp, evt.clientX, evt.clientY, evt.button, evt.buttons].join(\":\");",
      "  const visualTexDuplicatePointer = mathfield.visualTexLastPointerSignature === visualTexPointerSignature;",
      "  if (visualTexDuplicatePointer) return;",
      "  mathfield.visualTexLastPointerSignature = visualTexPointerSignature;",
    ].join("\n"),
    "deduplicate a physical pointer event at the MathLive selection entry point",
  );

  // Structural placeholder retention is part of the VisualTeX MathLive kernel
  // (node_modules/mathlive/mathlive.mjs), not injected here.

  // MathLive 0.109.2 can resolve a point visually inside a placeholder to an
  // adjacent structural boundary. Give real Placeholder/Prompt atoms first
  // refusal only when their own rendered bounds contain the pointer. All other
  // hit testing remains MathLive's native nearest-atom algorithm.
  patched = replaceExactly(
    patched,
    "  let atom = nearestAtomFromPoint(mathfield, x, y);",
    [
      "  const visualTexPlaceholderHit = mathfield.model.atoms.find((candidate) => {",
      '    if (candidate.type !== "placeholder" && candidate.type !== "prompt") return false;',
      "    const candidateBounds = getAtomBounds(mathfield, candidate);",
      "    return Boolean(candidateBounds && pointInRect(x, y, candidateBounds));",
      "  });",
      "  if (visualTexPlaceholderHit != null) return mathfield.model.offsetOf(visualTexPlaceholderHit);",
      "  let atom = nearestAtomFromPoint(mathfield, x, y);",
    ].join("\n"),
    "placeholder pointer hit testing",
  );

  patched = replaceExactly(
    patched,
    '  return model.deferNotifications(\n    { content: true, selection: true, type: "deleteContentBackward" },',
    '  const visualTexDeleteResult = model.deferNotifications(\n    { content: true, selection: true, type: "deleteContentBackward" },',
    "track backward delete result for variant lifecycle",
  );
  patched = replaceExactly(
    patched,
    '    }\n  );\n}\nfunction deleteForward(model) {',
    [
      '    }',
      '  );',
      '  if (model.mathfield.visualTexSourceWrapper) visualTexSyncSourceWrapper(model.mathfield);',
      '  return visualTexDeleteResult;',
      '}',
      'function deleteForward(model) {',
    ].join('\n'),
    "refresh variant state after backward delete transaction",
  );
  patched = replaceExactly(
    patched,
    '  return model.deferNotifications(\n    { content: true, selection: true, type: "deleteContentForward" },',
    '  const visualTexDeleteResult = model.deferNotifications(\n    { content: true, selection: true, type: "deleteContentForward" },',
    "track forward delete result for variant lifecycle",
  );
  patched = replaceExactly(
    patched,
    '    }\n  );\n}\nfunction deleteRange(model, range2, type) {',
    [
      '    }',
      '  );',
      '  if (model.mathfield.visualTexSourceWrapper) visualTexSyncSourceWrapper(model.mathfield);',
      '  return visualTexDeleteResult;',
      '}',
      'function deleteRange(model, range2, type) {',
    ].join('\n'),
    "refresh variant state after forward delete transaction",
  );

  // Backspace/Delete structural retention is implemented directly in the
  // VisualTeX MathLive kernel.

  patched = replaceExactly(
    patched,
    "function leap(model, dir) {",
    [
      "function visualTexIsBoundedOperatorParent(parent) {",
      "  if (!parent) return false;",
      '  if (parent.type === "mop" || parent.type === "operator" || parent.type === "extensible-symbol") return true;',
      '  if (parent.type !== "subsup") return false;',
      "  const base = parent.leftSibling;",
      '  return Boolean(base && (base.type === "error" || base.type === "mop" || base.type === "operator" || base.type === "extensible-symbol"));',
      "}",
      "function visualTexBoundedOperatorBranchPlaceholders(model, parent, branch) {",
      "  if (!visualTexIsBoundedOperatorParent(parent)) return [];",
      "  const branchAtoms = parent.branch(branch);",
      "  if (!branchAtoms) return [];",
      "  return branchAtoms.flatMap((atom) => [atom, ...atom.children]).filter((atom) => atom.type === \"placeholder\" || atom.type === \"prompt\");",
      "}",
      "function visualTexLeapBoundedOperatorForward(model, allowInternalPlaceholderJump = true) {",
      "  const selected = model.at(Math.max(model.position, model.anchor));",
      "  if (!selected) return false;",
      "  const parent = selected.parent;",
      "  const branch = selected.parentBranch;",
      '  if (!parent || (branch !== "subscript" && branch !== "superscript")) return false;',
      "  if (!visualTexIsBoundedOperatorParent(parent)) return false;",
      "  const lowerBranch = parent.branch(\"subscript\");",
      "  const upperBranch = parent.branch(\"superscript\");",
      "  if (!lowerBranch || !upperBranch) return false;",
      "  const lower = visualTexBoundedOperatorBranchPlaceholders(model, parent, \"subscript\");",
      "  const upper = visualTexBoundedOperatorBranchPlaceholders(model, parent, \"superscript\");",
      "  const currentOffset = model.offsetOf(selected);",
      "  const currentList = branch === \"subscript\" ? lower : upper;",
      "  const nextInBranch = currentList.find((atom) => model.offsetOf(atom) > currentOffset);",
      "  if (allowInternalPlaceholderJump && nextInBranch) return leapTo(model, nextInBranch);",
      "  if (!allowInternalPlaceholderJump && !selected.isLastSibling) return false;",
      "  if (branch === \"subscript\") return upper[0] ? leapTo(model, upper[0]) : false;",
      "  const operatorOffset = model.offsetOf(parent);",
      "  const target = leapTarget(model, operatorOffset + 1, \"forward\");",
      "  if (target && model.offsetOf(target) > operatorOffset) return leapTo(model, target);",
      "  return leapTo(model, parent);",
      "}",
      "function leap(model, dir) {",
      '  if (dir === "forward" && visualTexLeapBoundedOperatorForward(model)) return true;',
    ].join("\n"),
    "bounded operator placeholder leap order",
  );

  patched = replaceExactly(
    patched,
    '  options = options != null ? options : { extend: false };',
    [
      '  options = options != null ? options : { extend: false };',
      '  if (direction === "forward" && !(options == null ? void 0 : options.extend) && visualTexLeapBoundedOperatorForward(model, false)) return true;',
    ].join("\n"),
    "bounded operator ArrowRight model order",
  );

  patched = replaceExactly(
    patched,
    [
      '    moveToNextGroup: (model) => {',
      '      var _a3, _b3, _c2, _d2;',
    ].join("\n"),
    [
      '    moveToNextGroup: (model) => {',
      '      var _a3, _b3, _c2, _d2;',
      '      if (visualTexLeapBoundedOperatorForward(model)) return true;',
    ].join("\n"),
    "bounded operator Tab model order",
  );

  patched = replaceExactly(
    patched,
    [
      '      if (!placeholder) {',
      '        placeholder = newAtoms.flatMap((x) => [x, ...x.children]).find((x) => x.type === "placeholder");',
      '      }',
    ].join("\n"),
    [
      '      if (!placeholder) {',
      '        const visualTexBoundedOperator = newAtoms.flatMap((x) => [x, ...x.children]).find((x) => {',
      '          if (!visualTexIsBoundedOperatorParent(x)) return false;',
      '          const lower = x.branch("subscript");',
      '          const upper = x.branch("superscript");',
      '          const lowerPlaceholder = lower == null ? void 0 : lower.flatMap((atom) => [atom, ...atom.children]).find((atom) => atom.type === "placeholder" || atom.type === "prompt");',
      '          const upperPlaceholder = upper == null ? void 0 : upper.flatMap((atom) => [atom, ...atom.children]).find((atom) => atom.type === "placeholder" || atom.type === "prompt");',
      '          return Boolean(lowerPlaceholder && upperPlaceholder);',
      '        });',
      '        const lower = visualTexBoundedOperator == null ? void 0 : visualTexBoundedOperator.branch("subscript");',
      '        placeholder = lower == null ? void 0 : lower.flatMap((atom) => [atom, ...atom.children]).find((atom) => atom.type === "placeholder" || atom.type === "prompt");',
      '      }',
      '      if (!placeholder) {',
      '        placeholder = newAtoms.flatMap((x) => [x, ...x.children]).find((x) => x.type === "placeholder");',
      '      }',
    ].join("\n"),
    "bounded operator initial lower placeholder",
  );

  patched = replaceExactly(
    patched,
    "function insertMathModeChar(mathfield, c) {",
    [
      "function visualTexSelectFirstSemanticWrapperPlaceholder(mathfield, command) {",
      '  if (!["\\\\overset", "\\\\underset", "\\\\overunderset", "\\\\stackrel", "\\\\stackbin"].includes(command)) return false;',
      "  const model = mathfield.model;",
      "  let selected = model.at(Math.max(model.position, model.anchor));",
      '  if (!selected || (selected.type !== "placeholder" && selected.type !== "prompt")) return false;',
      "  let owner = selected.parent;",
      '  while (owner?.parent && owner.parent.type === "overunder") owner = owner.parent;',
      '  if (!owner || owner.type !== "overunder") return false;',
      "  const firstArgumentBranch = command === \"\\\\underset\" ? \"below\" : \"above\";",
      "  const branchAtoms = owner.branch(firstArgumentBranch) || [];",
      "  const target = branchAtoms",
      '    .flatMap((atom) => [atom, ...atom.children])',
      '    .find((atom) => atom.type === "placeholder" || atom.type === "prompt");',
      "  if (!target) return false;",
      "  const offset = model.offsetOf(target);",
      "  if (offset <= 0) return false;",
      "  model.setSelection(offset - 1, offset);",
      "  return true;",
      "}",
      "function visualTexCanonicalVariantInputCommand(command) {",
      "  return ({",
      '    "\\\\bf": "\\\\mathbf", "\\\\bfseries": "\\\\mathbf",',
      '    "\\\\it": "\\\\mathit", "\\\\rm": "\\\\mathrm", "\\\\sf": "\\\\mathsf", "\\\\tt": "\\\\mathtt",',
      '    "\\\\cal": "\\\\mathcal", "\\\\Bbb": "\\\\mathbb", "\\\\frak": "\\\\mathfrak",',
      '    "\\\\bold": "\\\\mathbfit", "\\\\boldmath": "\\\\mathbfit", "\\\\pmb": "\\\\mathbfit",',
      '    "\\\\simbfit": "\\\\symbfit",',
      "  })[command] || command;",
      "}",
      "function visualTexIsVariantInputCommand(command) {",
      "  const canonical = visualTexCanonicalVariantInputCommand(command);",
      '  return ["\\\\mathbf", "\\\\mathbb", "\\\\mathit", "\\\\mathrm", "\\\\mathsf", "\\\\mathtt", "\\\\mathcal", "\\\\mathscr", "\\\\mathfrak", "\\\\boldsymbol", "\\\\bm", "\\\\mathbfit", "\\\\mathnormal", "\\\\symup", "\\\\symit", "\\\\symbf", "\\\\symbfup", "\\\\symbfit", "\\\\symbb", "\\\\symcal", "\\\\symbfcal", "\\\\symscr", "\\\\symbfscr", "\\\\symfrak", "\\\\symbffrak", "\\\\symsfup", "\\\\symsfit", "\\\\symbfsfup", "\\\\symbfsfit", "\\\\symtt"].includes(canonical);',
      "}",
      "function visualTexIsAccentSourceCommand(command) {",
      '  return ["\\\\acute", "\\\\grave", "\\\\dot", "\\\\ddot", "\\\\dddot", "\\\\ddddot", "\\\\tilde", "\\\\bar", "\\\\breve", "\\\\check", "\\\\hat", "\\\\vec", "\\\\widehat", "\\\\widetilde", "\\\\overline", "\\\\overrightarrow", "\\\\overleftarrow", "\\\\overleftrightarrow", "\\\\mathring"].includes(command);',
      "}",
      "function visualTexSourceWrapperKind(command) {",
      "  const canonical = visualTexCanonicalVariantInputCommand(command);",
      '  if (visualTexIsVariantInputCommand(canonical)) return "variant";',
      '  if (visualTexIsAccentSourceCommand(canonical)) return "accent";',
      "  return null;",
      "}",
      "function visualTexSourceWrapperTemplate(input) {",
      '  if (typeof input !== "string") return null;',
      '  const match = input.match(/^(\\\\[a-zA-Z]+)\\{\\\\placeholder\\{\\}\\}$/);',
      "  if (!match) return null;",
      "  const command = visualTexCanonicalVariantInputCommand(match[1]);",
      "  const kind = visualTexSourceWrapperKind(command);",
      "  return kind ? { command, kind } : null;",
      "}",
      "function visualTexSourceWrapperRaw(state) {",
      "  const group = state?.group;",
      "  if (!group?.parent) return null;",
      '  return (group.body || []).filter((atom) => atom.type === "latex" && !atom.isSuggestion).map((atom) => atom.value).join("");',
      "}",
      "function visualTexSourceWrapperContent(state) {",
      "  const raw = visualTexSourceWrapperRaw(state);",
      "  const prefix = state?.command + \"{\";",
      '  if (raw == null || !raw.startsWith(prefix) || !raw.endsWith("}")) return null;',
      "  return raw.slice(prefix.length, -1);",
      "}",
      "function visualTexSyncSourceWrapper(mathfield) {",
      "  let state = mathfield.visualTexSourceWrapper;",
      "  if (state) {",
      "    const group = state.group;",
      "    const offset = group?.parent ? mathfield.model.offsetOf(group) : -1;",
      "    if (!group?.parent || offset < 0 || mathfield.model.at(offset) !== group) {",
      "      mathfield.visualTexSourceWrapper = null;",
      "      state = null;",
      "    }",
      "  }",
      "  const host = mathfield.host;",
      "  if (!host) return;",
      "  const content = state ? visualTexSourceWrapperContent(state) : null;",
      "  if (state && content != null) {",
      "    host.dataset.visualtexSourceWrapperCommand = state.command;",
      "    host.dataset.visualtexSourceWrapperKind = state.kind;",
      "    host.dataset.visualtexSourceWrapperContent = content;",
      "  } else {",
      "    delete host.dataset.visualtexSourceWrapperCommand;",
      "    delete host.dataset.visualtexSourceWrapperKind;",
      "    delete host.dataset.visualtexSourceWrapperContent;",
      "  }",
      "}",
      "function visualTexSourceWrapperAutoExitEnabled(mathfield, state) {",
      '  if (state?.kind === "accent") return (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitAccent) === "true";',
      '  return (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitWrapperCommand) !== "false";',
      "}",
      "function visualTexSourceWrapperCaretIsInside(mathfield, state) {",
      "  const current = mathfield.model.at(mathfield.model.position);",
      "  return Boolean(state?.group?.parent && (current === state.group || current?.parent === state.group));",
      "}",
      "function visualTexStartSourceWrapper(model, input, structuralSlot = null) {",
      "  const mathfield = model.mathfield;",
      "  const info = visualTexSourceWrapperTemplate(input);",
      "  if (!info) return false;",
      "  const shell = info.command + \"{}\";",
      "  const group = new LatexGroupAtom(shell);",
      "  const cursor = model.at(model.position);",
      "  if (!cursor?.parent) return false;",
      "  cursor.parent.addChildAfter(group, cursor);",
      "  const latexAtoms = (group.body || []).filter((atom) => atom.type === \"latex\");",
      "  const close = latexAtoms[latexAtoms.length - 1];",
      "  const beforeClose = close?.leftSibling;",
      "  if (!close || !beforeClose) {",
      "    group.parent?.removeChild(group);",
      "    return false;",
      "  }",
      "  const state = { command: info.command, kind: info.kind, group, structuralSlot };",
      "  group.visualTexSourceWrapper = state;",
      "  if (structuralSlot) group.visualTexStructuralSlot = structuralSlot;",
      "  mathfield.visualTexSourceWrapper = state;",
      '  // Keep the raw-shell selection private until the matching input event',
      '  // has updated host state. Publishing selection first can make a host',
      '  // render stale content and replace this live LatexGroup.',
      "  const visualTexSavedSilence = model.silenceNotifications;",
      "  model.silenceNotifications = true;",
      '  model.mode = "latex";',
      "  model.position = model.offsetOf(beforeClose);",
      "  model.silenceNotifications = visualTexSavedSilence;",
      "  if (!visualTexSavedSilence) mathfield.visualTexDeferredSelectionAfterInput = true;",
      "  visualTexSyncSourceWrapper(mathfield);",
      "  model.contentDidChange({ data: shell, inputType: \"insertText\" });",
      "  requestUpdate(mathfield);",
      "  return true;",
      "}",
      "function visualTexClearSourceWrapper(mathfield) {",
      "  if (!mathfield.visualTexSourceWrapper) return;",
      "  mathfield.visualTexSourceWrapper = null;",
      "  visualTexSyncSourceWrapper(mathfield);",
      "}",
      "function visualTexCancelSourceWrapper(mathfield) {",
      "  const state = mathfield.visualTexSourceWrapper;",
      "  const group = state?.group;",
      "  if (!state || !group?.parent) { visualTexClearSourceWrapper(mathfield); return false; }",
      "  const model = mathfield.model;",
      "  const parent = group.parent;",
      "  const branch = group.parentBranch;",
      "  const left = group.leftSibling;",
      "  parent.removeChild(group);",
      '  model.mode = "math";',
      "  model.position = Math.max(0, model.offsetOf(left));",
      "  visualTexClearSourceWrapper(mathfield);",
      "  if (state.structuralSlot?.parent &&",
      "      !visualTexStructuralSlotStillOccupied(state.structuralSlot.parent, state.structuralSlot.branch, state.structuralSlot)) {",
      "    visualTexRestoreStructuralPlaceholder(model, state.structuralSlot.parent, state.structuralSlot.branch, state.structuralSlot.after, true, state.structuralSlot);",
      "  } else if (visualTexShouldRetainStructuralPlaceholder(parent, branch) && parent.hasEmptyBranch(branch)) {",
      "    visualTexRestoreStructuralPlaceholder(model, parent, branch, left);",
      "  }",
      "  requestUpdate(mathfield);",
      "  return true;",
      "}",
      "function visualTexSourceWrapperSimpleCommand(mathfield, content) {",
      '  if (!/^\\\\[a-zA-Z]+\\*?$/.test(content)) return false;',
      "  const native = LATEX_COMMANDS[content];",
      "  if (MATH_SYMBOLS[content]) return true;",
      "  if (native && !(native.params || []).some((param) => !param.optional)) return true;",
      "  const macro = mathfield.options.macros?.[content.slice(1)];",
      '  return typeof macro === "string" && !/#\\d/.test(macro);',
      "}",
      "function visualTexCommitSourceWrapper(mathfield, { requireComplete = false, notify = true } = {}) {",
      "  const state = mathfield.visualTexSourceWrapper;",
      "  const group = state?.group;",
      "  if (!state || !group?.parent) { visualTexClearSourceWrapper(mathfield); return false; }",
      "  const content = visualTexSourceWrapperContent(state);",
      "  if (!content) return false;",
      "  if (requireComplete && Array.from(content).length !== 1 && !visualTexSourceWrapperSimpleCommand(mathfield, content)) return false;",
      "  const model = mathfield.model;",
      "  let command = state.command;",
      '  if (command === "\\\\mathcal" && /^[a-z]$/.test(content)) command = "\\\\mathscr";',
      "  const latex = command + \"{\" + content + \"}\";",
      "  const parsed = parseLatex(latex, { context: mathfield.context });",
      "  if (!parsed?.length) return false;",
      "  const parent = group.parent;",
      "  const left = group.leftSibling;",
      "  parent.removeChild(group);",
      "  const last = parent.addChildrenAfter(parsed, left);",
      "  if (state.structuralSlot) {",
      "    for (const atom of parsed) atom.visualTexStructuralSlot = state.structuralSlot;",
      "  }",
      "  const visualTexSavedSilence = model.silenceNotifications;",
      "  model.silenceNotifications = true;",
      '  model.mode = "math";',
      "  model.position = model.offsetOf(last);",
      "  model.silenceNotifications = visualTexSavedSilence;",
      "  visualTexClearSourceWrapper(mathfield);",
      "  if (notify && !visualTexSavedSilence)",
      "    mathfield.visualTexDeferredSelectionAfterInput = true;",
      "  mathfield.stopCoalescingUndo();",
      "  requestUpdate(mathfield);",
      "  if (notify) model.contentDidChange({ data: latex, inputType: \"insertText\" });",
      "  return true;",
      "}",
      "function visualTexMaybeAutoCommitSourceWrapper(mathfield) {",
      "  const state = mathfield.visualTexSourceWrapper;",
      "  if (!state || mathfield.visualTexCompositionCommit || !visualTexSourceWrapperCaretIsInside(mathfield, state)) return false;",
      "  if (!visualTexSourceWrapperAutoExitEnabled(mathfield, state)) { visualTexSyncSourceWrapper(mathfield); return false; }",
      "  const content = visualTexSourceWrapperContent(state);",
      "  visualTexSyncSourceWrapper(mathfield);",
      "  if (content == null || Array.from(content).length !== 1 || content === \"\\\\\") return false;",
      "  return visualTexCommitSourceWrapper(mathfield, { requireComplete: true, notify: false });",
      "}",
      "function visualTexAcceptSourceWrapperCompletion(mathfield) {",
      "  const state = mathfield.visualTexSourceWrapper;",
      "  const completion = mathfield.visualTexCompletion;",
      "  if (!state?.group?.parent || completion?.group !== state.group) return false;",
      "  const selected = completion.suggestions?.[mathfield.suggestionIndex];",
      "  if (!selected) return false;",
      "  const info = visualTexCompletionInfo(mathfield, selected);",
      '  const token = (info?.command || selected).match(/^\\\\[a-zA-Z]+\\*?/)?.[0];',
      "  if (!token) return false;",
      "  const model = mathfield.model;",
      "  let atom = model.at(model.position);",
      '  while (atom instanceof LatexAtom && /^[a-zA-Z\\*]$/.test(atom.value)) atom = atom.leftSibling;',
      '  if (!(atom instanceof LatexAtom) || atom.value !== "\\\\" || atom.parent !== state.group) return false;',
      "  const first = atom;",
      "  const commandAtoms = [first];",
      "  atom = first.rightSibling;",
      '  while (atom instanceof LatexAtom && /^[a-zA-Z\\*]$/.test(atom.value)) { commandAtoms.push(atom); atom = atom.rightSibling; }',
      "  const left = first.leftSibling;",
      "  if (!left) return false;",
      "  for (const item of commandAtoms) state.group.removeChild(item);",
      "  const visualTexTemplate = selected.startsWith(token) ? selected : token;",
      "  const visualTexSource = visualTexTemplate.replace(/\\\\placeholder\\{\\}/g, \"\");",
      "  const replacement = [...visualTexSource].map((value) => new LatexAtom(value));",
      "  const last = state.group.addChildrenAfter(replacement, left);",
      "  const visualTexEmptyArgument = visualTexSource.indexOf(\"{}\");",
      "  const visualTexCaretAtom = visualTexEmptyArgument >= 0",
      "    ? replacement[visualTexEmptyArgument]",
      "    : last;",
      "  model.position = model.offsetOf(visualTexCaretAtom);",
      "  mathfield.visualTexCompletion = null;",
      "  hideSuggestionPopover(mathfield);",
      "  visualTexSyncSourceWrapper(mathfield);",
      "  model.contentDidChange({ data: visualTexSource, inputType: \"insertText\" });",
      "  requestUpdate(mathfield);",
      "  return true;",
      "}",
      "function visualTexAutoExitAccentAfterDirectInput(mathfield, atom) {",
      "  if (mathfield.visualTexCompositionCommit) return false;",
      '  if ((mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitAccent) !== "true") return false;',
      '  const visualTexAutoExitAccentCommands = ["\\\\acute", "\\\\grave", "\\\\dot", "\\\\ddot", "\\\\dddot", "\\\\ddddot", "\\\\tilde", "\\\\bar", "\\\\breve", "\\\\check", "\\\\hat", "\\\\vec", "\\\\widehat", "\\\\widetilde", "\\\\overline", "\\\\overrightarrow", "\\\\overleftarrow", "\\\\overleftrightarrow", "\\\\mathring"];',
      '  if (atom?.type === "accent" && visualTexAutoExitAccentCommands.includes(atom.command)) {',
      "    const previousPosition = mathfield.model.position;",
      "    const target = mathfield.model.offsetOf(atom);",
      "    if (target >= 0 && target !== previousPosition) {",
      "      mathfield.model.position = target;",
      "      mathfield.stopCoalescingUndo();",
      '      mathfield.model.announce("move", previousPosition);',
      "      return true;",
      "    }",
      "  }",
      "  let current = atom;",
      "  while (current == null ? void 0 : current.parent) {",
      '    if (current.parent.type === "accent") {',
      "      if (!visualTexAutoExitAccentCommands.includes(current.parent.command)) return false;",
      "      if (current !== atom) return false;",
      "      const previousPosition = mathfield.model.position;",
      "      const target = mathfield.model.offsetOf(current.parent);",
      "      if (target < 0 || target === previousPosition) return false;",
      "      mathfield.model.position = target;",
      "      mathfield.stopCoalescingUndo();",
      '      mathfield.model.announce("move", previousPosition);',
      "      return true;",
      "    }",
      "    current = current.parent;",
      "  }",
      "  return false;",
      "}",
      "function visualTexAutoExitAfterComposition(mathfield, slot) {",
      "  if (!slot?.parent) return false;",
      "  const model = mathfield.model;",
      "  const parent = slot.parent;",
      "  const branch = slot.branch;",

      '  const accentCommands = ["\\\\acute", "\\\\grave", "\\\\dot", "\\\\ddot", "\\\\dddot", "\\\\ddddot", "\\\\tilde", "\\\\bar", "\\\\breve", "\\\\check", "\\\\hat", "\\\\vec", "\\\\widehat", "\\\\widetilde", "\\\\overline", "\\\\overrightarrow", "\\\\overleftarrow", "\\\\overleftrightarrow", "\\\\mathring"];',
      '  if (parent.type === "accent" && branch === "body" &&',
      '      (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitAccent) === "true" &&',
      "      accentCommands.includes(parent.command)) {",
      "    const previous = model.position;",
      "    const target = model.offsetOf(parent);",
      "    if (target >= 0 && target !== previous) {",
      "      model.position = target;",
      "      mathfield.stopCoalescingUndo();",
      '      model.announce("move", previous);',
      "      return true;",
      "    }",
      "  }",
      '  if (branch !== "superscript" && branch !== "subscript") return false;',
      "  if (visualTexIsBoundedOperatorParent(parent)) {",
      '    if (branch === "subscript") {',
      '      const upper = visualTexBoundedOperatorBranchPlaceholders(model, parent, "superscript");',
      "      return upper[0] ? leapTo(model, upper[0]) : false;",
      "    }",
      "    const operatorOffset = model.offsetOf(parent);",
      '    const target = leapTarget(model, operatorOffset + 1, "forward");',
      '    if (target && model.offsetOf(target) > operatorOffset) return leapTo(model, target);',
      "    return leapTo(model, parent);",
      "  }",
      '  const enabled = branch === "superscript"',
      '    ? (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitSuperscript) === "true"',
      '    : (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitSubscript) === "true";',
      "  if (!enabled || !parent.parent) return false;",
      "  const previous = model.position;",
      "  const target = model.offsetOf(parent);",
      "  if (target < 0 || target === previous) return false;",
      "  model.position = target;",
      "  mathfield.stopCoalescingUndo();",
      '  model.announce("move", previous);',
      "  return true;",
      "}",
      "function visualTexScriptAutoExitKey(mathfield, atom) {",
      "  const branch = atom == null ? void 0 : atom.parentBranch;",
      '  if (branch !== "superscript" && branch !== "subscript") return null;',
      "  const parent = atom == null ? void 0 : atom.parent;",
      "  if (!parent) return null;",
      "  if (visualTexIsBoundedOperatorParent(parent)) return null;",
      '  const enabled = branch === "superscript"',
      '    ? (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitSuperscript) === "true"',
      '    : (mathfield.host == null ? void 0 : mathfield.host.dataset.visualtexAutoExitSubscript) === "true";',
      "  if (!enabled) return null;",
      "  const branchAtoms = parent.branch(branch);",
      "  const branchId = (branchAtoms == null ? void 0 : branchAtoms[0] == null ? void 0 : branchAtoms[0].id) || parent.id;",
      "  return branchId ? `${branch}:${branchId}` : null;",
      "}",
      "function visualTexAutoExitScriptAfterDirectInput(mathfield, atom) {",
      "  if (mathfield.visualTexCompositionCommit) return false;",
      "  const key = visualTexScriptAutoExitKey(mathfield, atom);",
      "  if (!key) return false;",
      "  let consumed = mathfield.visualTexConsumedScriptAutoExitKeys;",
      "  if (!consumed) {",
      "    consumed = /* @__PURE__ */ new Set();",
      "    mathfield.visualTexConsumedScriptAutoExitKeys = consumed;",
      "  }",
      "  if (consumed.has(key)) return false;",
      "  consumed.add(key);",
      "  const parent = atom == null ? void 0 : atom.parent;",
      "  if (!parent || !parent.parent) return false;",
      "  const model = mathfield.model;",
      "  const previousPosition = model.position;",
      "  const targetPosition = model.offsetOf(parent);",
      "  if (targetPosition < 0 || targetPosition === previousPosition) return false;",
      "  model.position = targetPosition;",
      "  model.mathfield.stopCoalescingUndo();",
      '  model.announce("move", previousPosition);',
      "  return true;",
      "}",
      "function insertMathModeChar(mathfield, c) {",
    ].join("\n"),
    "script auto-exit helper",
  );

  patched = replaceExactly(
    patched,
    '  let placeholderReplaced = false;\n  if (mathfield.isSelectionEditable && model.selectionIsPlaceholder && mightProducePrintableCharacter(evt)) {',
    [
      '  let placeholderReplaced = false;',
      '  mathfield.visualTexPendingPlaceholderSelection = null;',
      '  if (mathfield.isSelectionEditable && model.selectionIsPlaceholder && mightProducePrintableCharacter(evt)) {',
      '    const selected = model.at(Math.max(model.position, model.anchor));',
      '    // A direct glyph replacement is not a continuation of a previous raw command.',
      '    mathfield.visualTexPendingStructuralCommandSlot = null;',
      '    mathfield.visualTexPendingPlaceholderSelection = {',
      '      position: Math.min(model.position, model.anchor),',
      '      style: { ...selected.style },',
      '      slot: visualTexFreshStructuralSlot(selected),',
      '    };',
    ].join('\n'),
    "remember placeholder style before MathLive handles printable input",
  );

  patched = replaceExactly(
    patched,
    [
      '    mathfield.flushInlineShortcutBuffer();',
      '    model.deleteAtoms(range(model.selection));',
      '    mathfield.snapshot("delete");',
      '    placeholderReplaced = true;',
    ].join('\n'),
    [
      '    // Keep the placeholder alive until the actual insert transaction.',
      '    // If beforeinput is cancelled, the model must remain byte-for-byte unchanged.',
      '    mathfield.flushInlineShortcutBuffer();',
      '    placeholderReplaced = true;',
    ].join('\n'),
    "placeholder replacement is committed by insertion, not keydown",
  );

  patched = replaceExactly(
    patched,
    '  if (selector) mathfield.executeCommand(selector);\n  else if (shortcut) {',
    '  if (selector) mathfield.executeCommand(selector);\n  else if (shortcut) {',
    "native delete and navigation stay in MathLive",
  );

  patched = replaceExactly(
    patched,
    '    if (!selector && (keystroke === "[Enter]" || keystroke === "[Return]")) {',
    [
      '    if (mathfield.visualTexSourceWrapper &&',
      '        (keystroke === "[Enter]" || keystroke === "[Return]")) {',
      '      const visualTexCommittedSourceWrapper = visualTexCommitSourceWrapper(mathfield);',
      '      if (visualTexCommittedSourceWrapper) {',
      '        mathfield.snapshot("insert-source-wrapper");',
      '        mathfield.model.announce("replacement");',
      '      }',
      '      if (evt.preventDefault) evt.preventDefault();',
      '      if (evt.stopPropagation) evt.stopPropagation();',
      '      return false;',
      '    }',
      '    if (mathfield.visualTexSourceWrapper && keystroke === "[Backspace]" &&',
      '        visualTexSourceWrapperContent(mathfield.visualTexSourceWrapper) === "") {',
      '      visualTexCancelSourceWrapper(mathfield);',
      '      mathfield.snapshot("delete-source-wrapper");',
      '      if (evt.preventDefault) evt.preventDefault();',
      '      if (evt.stopPropagation) evt.stopPropagation();',
      '      return false;',
      '    }',
      '    if (!selector && (keystroke === "[Enter]" || keystroke === "[Return]")) {',
    ].join('\n'),
    "Enter confirms persistent variant input without creating a formula row",
  );

  patched = replaceExactly(
    patched,
    [
      '  insert(model, input, options) {',
      '    var _a3, _b3, _c2, _d2;',
      '    const data = typeof input === "string" ? input : (_b3 = (_a3 = globalThis.MathfieldElement.computeEngine) == null ? void 0 : _a3.box(input).latex) != null ? _b3 : "";',
      '    if (!options.silenceNotifications && !model.contentWillChange({ data, inputType: "insertText" }))',
      '      return false;',
      '    if (!options.insertionMode) options.insertionMode = "replaceSelection";',
    ].join('\n'),
    [
      '  insert(model, input, options) {',
      '    var _a3, _b3, _c2, _d2;',
      '    const data = typeof input === "string" ? input : (_b3 = (_a3 = globalThis.MathfieldElement.computeEngine) == null ? void 0 : _a3.box(input).latex) != null ? _b3 : "";',
      '    if (!options.silenceNotifications && !model.contentWillChange({ data, inputType: "insertText" }))',
      '      return false;',
      '    const visualTexReplacingAll = options.insertionMode === "replaceAll";',
      '    if (visualTexReplacingAll) {',
      '      model.mathfield.visualTexPendingStructuralCommandSlot = null;',
      '      model.mathfield.visualTexPendingPlaceholderSelection = null;',
      '      if (model.mathfield.visualTexSourceWrapper) visualTexClearSourceWrapper(model.mathfield);',
      '    }',
      '    const visualTexInsertionAnchor = model.at(model.position);',
      '    const visualTexSelectedPlaceholder = model.selectionIsPlaceholder',
      '      ? model.at(Math.max(model.position, model.anchor))',
      '      : null;',
      '    const visualTexPendingCommandSlot = model.mathfield.visualTexPendingStructuralCommandSlot;',
      '    let visualTexStructuralSlot = null;',
      '    if (!visualTexReplacingAll && visualTexSelectedPlaceholder?.type === "placeholder") {',
      '      visualTexStructuralSlot = visualTexFreshStructuralSlot(visualTexSelectedPlaceholder);',
      '    } else if (!visualTexReplacingAll && visualTexPendingCommandSlot) {',
      '      visualTexStructuralSlot = visualTexPendingCommandSlot;',
      '      if (visualTexInsertionAnchor?.parent && visualTexPendingCommandSlot.parent !== visualTexInsertionAnchor.parent) {',
      '        visualTexStructuralSlot = {',
      '          ...visualTexPendingCommandSlot,',
      '          parent: visualTexInsertionAnchor.parent,',
      '          branch: visualTexInsertionAnchor.parentBranch,',
      '          after: visualTexInsertionAnchor,',
      '        };',
      '      }',
      '    } else if (!visualTexReplacingAll) {',
      '      visualTexStructuralSlot = visualTexLiveStructuralSlot(visualTexInsertionAnchor);',
      '    }',
      '    model.mathfield.visualTexPendingStructuralCommandSlot = null;',
      '    const visualTexSourceWrapper = !visualTexReplacingAll ? visualTexSourceWrapperTemplate(input) : null;',
      '    if (visualTexSourceWrapper) {',
      '      if (options.insertionMode === "replaceSelection" && !model.selectionIsCollapsed) {',
      '        const visualTexSourceStart = Math.min(model.position, model.anchor);',
      '        model.deleteAtoms(range(model.selection));',
      '        model.position = Math.max(0, Math.min(model.lastOffset, visualTexSourceStart));',
      '      } else if (options.insertionMode === "insertBefore") {',
      '        model.collapseSelection("backward");',
      '      } else if (options.insertionMode === "insertAfter") {',
      '        model.collapseSelection("forward");',
      '      }',
      '      if (visualTexStartSourceWrapper(model, input, visualTexStructuralSlot)) return true;',
      '    }',
      '    if (!options.insertionMode) options.insertionMode = "replaceSelection";',
    ].join('\n'),
    "ModeEditor insert remembers selected structural slot",
  );

  patched = replaceExactly(
    patched,
    '    const lastNewAtom = newAtoms[newAtoms.length - 1];',
    [
      '    const lastNewAtom = newAtoms[newAtoms.length - 1];',
      '    if (visualTexStructuralSlot) {',
      '      for (const visualTexInserted of newAtoms) visualTexInserted.visualTexStructuralSlot = visualTexStructuralSlot;',
      '    }',
    ].join('\n'),
    "single inserted structure inherits the replaced structural slot",
  );

  patched = replaceExactly(
    patched,
    '        if ((parent == null ? void 0 : parent.type) === "root" && hadEmptyBody && !usedArg)\n          parent.verbatimLatex = input;',
    [
      '        // A typed glyph can inherit a variant from the placeholder it replaces.',
      '        // Raw input is then no longer the full LaTeX serialization.',
      '        const visualTexPersistentStyledInsertion = newAtoms.some((atom) =>',
      '          Boolean(atom.visualTexPersistentTypingApplied));',
      '        if ((parent == null ? void 0 : parent.type) === "root" && hadEmptyBody && !usedArg &&',
      '            (!options.style || Object.keys(options.style).length === 0) &&',
      '            !visualTexPersistentStyledInsertion)',
      '          parent.verbatimLatex = input;',
    ].join('\n'),
    "styled insertion must not cache unstyled root LaTeX",
  );

  patched = replaceExactly(
    patched,
    '  const wasPlaceholderSelected = model.selectionIsPlaceholder;\n  if (/\\d/.test(c) && mathfield.options.smartSuperscript',
    [
      '  const wasPlaceholderSelected = model.selectionIsPlaceholder;',
      '  const visualTexInheritedStructuralSlot = visualTexLiveStructuralSlot(model.at(model.position));',
      '  const pendingPlaceholder = mathfield.visualTexPendingPlaceholderSelection;',
      '  mathfield.visualTexPendingPlaceholderSelection = null;',
      '  const replacedPlaceholder = wasPlaceholderSelected || pendingPlaceholder?.position === model.position;',
      '  // A font command such as \\mathbb is represented by style on its',
      '  // placeholder atom. Replacing that atom must carry the style to the',
      '  // typed glyph; otherwise the whole variant silently disappears.',
      '  if (replacedPlaceholder && /[a-zA-Z0-9]/.test(c)) {',
      '    const selectedPlaceholder = wasPlaceholderSelected ? model.at(Math.max(model.position, model.anchor)) : null;',
      '    Object.assign(style, selectedPlaceholder?.style || pendingPlaceholder?.style || {});',
      '  }',
      '  if (/\\d/.test(c) && mathfield.options.smartSuperscript',
    ].join('\n'),
    "styled placeholder passes variant to typed glyph",
  );

  patched = replaceExactly(
    patched,
    [
      "  mathfield.snapshot(`insert-${model.at(model.position).type}`);",
      "  if (/\\d/.test(c)) {",
    ].join("\n"),
    [
      "  const visualTexInsertedAtom = model.at(model.position);",
      "  if (visualTexInsertedAtom && (pendingPlaceholder?.slot || visualTexInheritedStructuralSlot)) {",
      "    visualTexInsertedAtom.visualTexStructuralSlot = pendingPlaceholder?.slot || visualTexInheritedStructuralSlot;",
      "  }",
      "  mathfield.snapshot(`insert-${visualTexInsertedAtom.type}`);",
      "  if (!visualTexAutoExitAccentAfterDirectInput(mathfield, visualTexInsertedAtom))",
      "    visualTexAutoExitScriptAfterDirectInput(mathfield, visualTexInsertedAtom);",
      "  if (/\\d/.test(c)) {",
    ].join("\n"),
    "script auto-exit after direct character",
  );

  // Fraction-local deletion and selected-branch retention now live in the
  // VisualTeX MathLive kernel. Placeholder-only deletion is intentionally
  // never reconstructed.

  patched = replaceExactly(patched,
    '    const previousMode = model.mode;\n    model.mode = mode;',
    [
      '    if (mode === "latex" && model.selectionIsPlaceholder) {',
      '      const selectedPlaceholder = model.at(Math.max(model.position, model.anchor));',
      '      if (selectedPlaceholder?.type === "placeholder") {',
      '        this.visualTexPendingStructuralCommandSlot = visualTexFreshStructuralSlot(selectedPlaceholder);',
      '      }',
      '    }',
      '    if (mode === "latex" && model.selectionIsCollapsed) {',
      '      const at = model.at(model.position);',
      '      const placeholder = at?.type === "placeholder" ? at : at?.rightSibling?.type === "placeholder" ? at.rightSibling : null;',
      '      if (placeholder) {',
      '        this.visualTexPendingStructuralCommandSlot = visualTexFreshStructuralSlot(placeholder);',
      '        model.setSelection(model.offsetOf(placeholder.leftSibling), model.offsetOf(placeholder));',
      '      } else if (visualTexLiveStructuralSlot(at)) {',
      '        this.visualTexPendingStructuralCommandSlot = visualTexLiveStructuralSlot(at);',
      '      }',
      '    }',
      '    const previousMode = model.mode;',
      '    model.mode = mode;',
    ].join('\n'), "latex mode carries the structural slot through command input");

  patched = replaceExactly(patched,
    '        const getContent = () => {',
    '        let visualTexReplacingPlaceholder = false;\n        const getContent = () => {',
    "track placeholder replacement when entering command mode");
  patched = replaceExactly(patched,
    '          if (atoms.length === 1 && atoms[0].type === "placeholder")\n            content = suffix;',
    '          if (atoms.length === 1 && atoms[0].type === "placeholder") {\n            visualTexReplacingPlaceholder = true;\n            content = suffix;\n          }',
    "placeholder command prefix is new input, not selected content");
  patched = replaceExactly(patched,
    '          if (mode === "latex") insertLatexGroup(content, { select: true });',
    '          if (mode === "latex") insertLatexGroup(content, { select: !visualTexReplacingPlaceholder });',
    "retain command prefix after replacing an adjacent placeholder");

  // VisualTeX IME composition semantics live directly in the project-owned
  // MathLive kernel (vendor/mathlive/kernel-parts/part-027.mjsfrag).

  patched = replaceExactly(
    patched,
    '      atom.caret = void 0;\n      atom.isSelected = false;\n      atom.containsCaret = false;',
    '      atom.caret = void 0;\n      atom.isSelected = false;\n      atom.containsCaret = false;\n      atom.visualTexPlaceholderCaret = false;',
    "reset core placeholder caret ownership",
  );
  patched = replaceExactly(
    patched,
    '      for (const atom of atoms) atom.isSelected = true;',
    [
      '      for (const atom of atoms) atom.isSelected = true;',
      '      if (model.selectionIsPlaceholder) {',
      '        const placeholder = model.at(Math.max(model.position, model.anchor));',
      '        if (placeholder?.type === "placeholder" || placeholder?.type === "prompt")',
      '          placeholder.visualTexPlaceholderCaret = true;',
      '      }',
    ].join('\n'),
    "only exact placeholder selection owns a caret",
  );
  patched = replaceExactly(
    patched,
    [
      '    return {',
      '      content: this.root.toJson(),',
      '      selection,',
      '      mode: this.mode',
      '    };',
    ].join('\n'),
    [
      '    const visualTexSourceWrapper = this.mathfield.visualTexSourceWrapper;',
      '    const visualTexSourceWrapperGroup = visualTexSourceWrapper?.group;',
      '    const visualTexSourceWrapperOffset = visualTexSourceWrapperGroup?.parent',
      '      ? this.offsetOf(visualTexSourceWrapperGroup)',
      '      : -1;',
      '    return {',
      '      content: this.root.toJson(),',
      '      selection,',
      '      mode: this.mode,',
      '      visualTexSourceWrapper: visualTexSourceWrapperOffset >= 0 ? {',
      '        command: visualTexSourceWrapper.command,',
      '        kind: visualTexSourceWrapper.kind,',
      '        groupOffset: visualTexSourceWrapperOffset,',
      '        hadStructuralSlot: Boolean(visualTexSourceWrapper.structuralSlot),',
      '      } : null,',
      '    };',
    ].join('\n'),
    "source wrapper participates in MathLive model history",
  );
  patched = replaceExactly(
    patched,
    [
      '      this.mode = state.mode;',
      '      this.root = fromJson(state.content);',
      '      this.selection = state.selection;',
    ].join('\n'),
    [
      '      this.mode = state.mode;',
      '      if (this.mathfield.visualTexSourceWrapper)',
      '        visualTexClearSourceWrapper(this.mathfield);',
      '      this.root = fromJson(state.content);',
      '      const visualTexSourceWrapperState = state.visualTexSourceWrapper;',
      '      if (visualTexSourceWrapperState) {',
      '        const visualTexSourceWrapperGroup = this.at(visualTexSourceWrapperState.groupOffset);',
      '        if (visualTexSourceWrapperGroup?.type === "latexgroup") {',
      '          const visualTexStructuralSlot = visualTexSourceWrapperState.hadStructuralSlot && visualTexSourceWrapperGroup.parent',
      '            ? {',
      '                parent: visualTexSourceWrapperGroup.parent,',
      '                branch: visualTexSourceWrapperGroup.parentBranch,',
      '                after: visualTexSourceWrapperGroup.leftSibling,',
      '              }',
      '            : null;',
      '          const visualTexRestoredSourceWrapper = {',
      '            command: visualTexSourceWrapperState.command,',
      '            kind: visualTexSourceWrapperState.kind,',
      '            group: visualTexSourceWrapperGroup,',
      '            structuralSlot: visualTexStructuralSlot,',
      '          };',
      '          visualTexSourceWrapperGroup.visualTexSourceWrapper = visualTexRestoredSourceWrapper;',
      '          if (visualTexStructuralSlot)',
      '            visualTexSourceWrapperGroup.visualTexStructuralSlot = visualTexStructuralSlot;',
      '          this.mathfield.visualTexSourceWrapper = visualTexRestoredSourceWrapper;',
      '          visualTexSyncSourceWrapper(this.mathfield);',
      '        }',
      '      }',
      '      this.selection = state.selection;',
    ].join('\n'),
    "source wrapper rebinds after undo redo model restore",
  );
  patched = replaceExactly(
    patched,
    [
      '    let [format, newAtoms] = convertStringToAtoms(',
      '      model,',
      '      input,',
      '      argFunction,',
      '      options',
      '    );',
      '    if (!newAtoms) return false;',
      '    const insertingFraction = newAtoms.length === 1 && newAtoms[0].type === "genfrac";',
    ].join("\n"),
    [
      '    let [format, newAtoms] = convertStringToAtoms(',
      '      model,',
      '      input,',
      '      argFunction,',
      '      options',
      '    );',
      '    if (!newAtoms) return false;',
      '    // Persistent typing format is applied only to genuinely new glyphs.',
      '    // A toolbar wrapper that reuses #0 keeps the selected content untouched.',
      '    if (!usedArg) visualTexApplyPersistentTypingStyle(model.mathfield, newAtoms);',
      '    const insertingFraction = newAtoms.length === 1 && newAtoms[0].type === "genfrac";',
    ].join("\n"),
    "apply persistent typing format to newly inserted math glyphs",
  );
  patched = replaceExactly(
    patched,
    [
      '    const newAtoms = convertStringToAtoms2(text, model.mathfield.context);',
      '    applyStyleToUnstyledAtoms(newAtoms, options.style);',
      '    if (!newAtoms) return false;',
      '    const cursor = model.at(model.position);',
    ].join("\n"),
    [
      '    const newAtoms = convertStringToAtoms2(text, model.mathfield.context);',
      '    applyStyleToUnstyledAtoms(newAtoms, options.style);',
      '    if (!newAtoms) return false;',
      '    visualTexApplyPersistentTypingStyle(model.mathfield, newAtoms);',
      '    const cursor = model.at(model.position);',
    ].join("\n"),
    "apply persistent typing format to newly inserted text glyphs",
  );
  patched = patchVisualTexMathLiveSelection(patchVisualTexMathLiveEditingKernel(patched));
  patched = replaceExactly(
    patched,
    "    let result = \"\";\n    if (props.length > 0 || svgMarkup.length > 0)\n      result = `<span ${props.join(\" \")}>${body}${svgMarkup}</span>`;\n    else result = body;\n    if (this.caret === \"text\") result += '<span class=\"ML__text-caret\"></span>';\n    else if (this.caret === \"math\") result += '<span class=\"ML__caret\"></span>';",
    "    let result = \"\";\n    const visualTexInlineCaret = this.caret === \"math\" && this.classes.split(\" \").includes(\"visualtex-structural-placeholder\")\n      ? '<span class=\"ML__caret visualtex-structural-placeholder-caret\"></span>'\n      : \"\";\n    if (props.length > 0 || svgMarkup.length > 0)\n      result = `<span ${props.join(\" \")}>${visualTexInlineCaret}${body}${svgMarkup}</span>`;\n    else result = body;\n    if (!visualTexInlineCaret) {\n      if (this.caret === \"text\") result += '<span class=\"ML__text-caret\"></span>';\n      else if (this.caret === \"math\") result += '<span class=\"ML__caret\"></span>';\n    }",
    "placeholder caret is emitted inside the placeholder box",
  );
  patched = replaceExactly(
    patched,
    '      this.mathfield.host.dispatchEvent(\n        new InputEvent("input", __spreadProps(__spreadValues({}, options), {\n          // To work around a bug in WebKit/Safari (the inputType property gets stripped), include the inputType as the \'data\' property. (see #1843)\n          data: options.data ? options.data : (_a4 = options.inputType) != null ? _a4 : "",\n          bubbles: true,\n          composed: true\n        }))\n      );',
    [
      '      this.mathfield.host.dispatchEvent(',
      '        new InputEvent("input", __spreadProps(__spreadValues({}, options), {',
      '          // To work around a bug in WebKit/Safari (the inputType property gets stripped), include the inputType as the \'data\' property. (see #1843)',
      '          data: options.data ? options.data : (_a4 = options.inputType) != null ? _a4 : "",',
      '          bubbles: true,',
      '          composed: true',
      '        }))',
      '      );',
      '      if (this.mathfield.visualTexDeferredSelectionAfterInput) {',
      '        this.mathfield.visualTexDeferredSelectionAfterInput = false;',
      '        this.selectionDidChange();',
      '      }',
    ].join('\n'),
    "source wrapper publishes selection after input state",
  );

  patched = replaceExactly(
    patched,
    '    model.silenceNotifications = saveSilenceNotifications;\n    if (options.selectionMode === "before") {',
    [
      '    const visualTexSourceWrapperSelectionPending = Boolean(model.mathfield.visualTexSourceWrapper);',
      '    if (!visualTexSourceWrapperSelectionPending)',
      '      model.silenceNotifications = saveSilenceNotifications;',
      '    if (options.selectionMode === "before") {',
    ].join('\n'),
    "source wrapper keeps raw caret mutation silent until input",
  );

  patched = replaceExactly(
    patched,
    '    model.contentDidChange({ data: text, inputType: "insertText" });\n    model.silenceNotifications = silenceNotifications;\n    return true;\n  }\n};\nfunction getLatexGroup(model) {',
    [
      '    if (visualTexSourceWrapperSelectionPending)',
      '      visualTexMaybeAutoCommitSourceWrapper(model.mathfield);',
      '    if (visualTexSourceWrapperSelectionPending) {',
      '      model.silenceNotifications = saveSilenceNotifications;',
      '      if (!saveSilenceNotifications)',
      '        model.mathfield.visualTexDeferredSelectionAfterInput = true;',
      '    }',
      '    model.contentDidChange({ data: text, inputType: "insertText" });',
      '    model.silenceNotifications = silenceNotifications;',
      '    return true;',
      '  }',
      '};',
      'function getLatexGroup(model) {',
    ].join('\n'),
    "raw source wrapper auto-commits only after a complete direct token",
  );

  patched = replaceExactly(
    patched,
    '    if (keystroke === "[Space]" && model.mode === "latex") {\n      if (complete(mathfield, "accept-all")) {',
    [
      '    if (keystroke === "[Space]" && model.mode === "latex" && mathfield.visualTexSourceWrapper) {',
      '      const visualTexState = mathfield.visualTexSourceWrapper;',
      '      const visualTexGroup = getLatexGroup(model);',
      '      if (visualTexGroup === visualTexState.group) {',
      '        const visualTexAcceptedSuggestion = visualTexAcceptSourceWrapperCompletion(mathfield);',
      '        visualTexSyncSourceWrapper(mathfield);',
      '        const visualTexContent = visualTexSourceWrapperContent(visualTexState);',
      '        const visualTexCanCommit = visualTexSourceWrapperAutoExitEnabled(mathfield, visualTexState) &&',
      '          (Array.from(visualTexContent || "").length === 1 || visualTexSourceWrapperSimpleCommand(mathfield, visualTexContent || ""));',
      '        if (visualTexCanCommit) {',
      '          visualTexCommitSourceWrapper(mathfield);',
      '          mathfield.snapshot("insert-source-wrapper");',
      '          mathfield.model.announce("replacement");',
      '        } else if (visualTexAcceptedSuggestion) {',
      '          mathfield.snapshot("insert-latex-suggestion");',
      '          requestUpdate(mathfield);',
      '        }',
      '        mathfield.dirty = true;',
      '        mathfield.scrollIntoView();',
      '        if (evt.preventDefault) { evt.preventDefault(); evt.stopPropagation(); }',
      '        return false;',
      '      }',
      '    }',
      '    if (keystroke === "[Space]" && model.mode === "latex") {',
      '      if (complete(mathfield, "accept-all")) {',
    ].join('\n'),
    "source wrapper Space accepts an inner raw command before rendering the wrapper",
  );

  patched = replaceExactly(
    patched,
    '  field.innerHTML = globalThis.MathfieldElement.createHTML(content);\n  renderSelection(mathfield, renderOptions.interactive);',
    [
      '  field.innerHTML = globalThis.MathfieldElement.createHTML(content);',
      '  mathfield.container?.classList.toggle("has-visualtex-raw-latex-command", mathfield.model.mode === "latex");',
      '  renderSelection(mathfield, renderOptions.interactive);',
    ].join('\n'),
    "render core-owned placeholder and variant carets",
  );
  return patchVisualTexMathLiveSemanticCompletion(patched);
}
