import { mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { latexToMathMl, latexToSvg } from "../src/export/latexToSvg.ts";
import type { FormulaLetterFont } from "../src/editor/formulaFontPreferences.ts";

type FixtureDefinition = {
  name: string;
  latex: string;
};

type FixtureItem = {
  name: string;
  latex: string;
  svgPath: string;
  width: number;
  height: number;
  baseline: number;
  mathMl: string;
  anchorMathMl: string;
  fontSizePt: number;
  formulaLetterFont: FormulaLetterFont;
  ommlFormulaLetterFont: FormulaLetterFont;
  formulaChineseFont: "system";
  safetyPaddingPixels: number;
  comparisonMode: "full-formula" | "anchor-only";
  compactLine: boolean;
};

const structureFormulas: FixtureDefinition[] = [
  { name: "plain-x", latex: String.raw`x` },
  { name: "plain-L", latex: String.raw`L` },
  { name: "subscript", latex: String.raw`L_z` },
  { name: "superscript", latex: String.raw`L^2` },
  { name: "both-scripts", latex: String.raw`L_z^2` },
  { name: "mixed-scripts", latex: String.raw`L_zL^2` },
  { name: "fraction", latex: String.raw`\frac{1}{2}` },
  { name: "nested-fraction", latex: String.raw`\cfrac{1}{1+\cfrac{1}{x}}` },
  { name: "square-root", latex: String.raw`\sqrt{x}` },
  { name: "indexed-root", latex: String.raw`\sqrt[3]{\frac{x+1}{y-1}}` },
  { name: "integral", latex: String.raw`\int_a^b c\,\mathrm{d}e` },
  { name: "summation", latex: String.raw`\sum_{n=1}^{\infty}\frac{1}{n^2}` },
  {
    name: "matrix",
    latex: String.raw`\left(\begin{matrix}a&b\\c&d\end{matrix}\right)`,
  },
  {
    name: "cases",
    latex: String.raw`\begin{cases}x^2,&x\ge 0\\-x,&x<0\end{cases}`,
  },
  {
    name: "overbrace",
    latex: String.raw`\overbrace{a+b+\cdots+z}^{26\text{ terms}}`,
  },
  {
    name: "underbrace",
    latex: String.raw`\underbrace{x_1+\cdots+x_n}_{n\text{ terms}}`,
  },
  {
    name: "accents",
    latex: String.raw`\hat{x}+\vec{y}+\overline{AB}`,
  },
  {
    name: "nested",
    latex: String.raw`\frac{\sqrt{x_i^2+y_i^2}}{\displaystyle\sum_{j=1}^{n}a_j}`,
  },
  {
    name: "mixed-chinese",
    latex: String.raw`\text{速度 }v=\frac{\mathrm{d}x}{\mathrm{d}t}`,
  },
];

const sizeFormulas: FixtureDefinition[] = [
  { name: "plain-x", latex: String.raw`x` },
  { name: "mixed-scripts", latex: String.raw`L_zL^2` },
  { name: "fraction", latex: String.raw`\frac{1}{2}` },
  { name: "square-root", latex: String.raw`\sqrt{x^2+y^2}` },
  { name: "integral", latex: String.raw`\int_a^b c\,\mathrm{d}e` },
  { name: "summation", latex: String.raw`\sum_{n=1}^{\infty}\frac{1}{n^2}` },
];

const fontFormulas: FixtureDefinition[] = [
  { name: "mixed-scripts", latex: String.raw`L_zL^2` },
  { name: "fraction", latex: String.raw`\frac{a+b}{c+d}` },
  { name: "integral", latex: String.raw`\int_a^b c\,\mathrm{d}e` },
];

const allFontChoices: FormulaLetterFont[] = [
  "katex",
  "times",
  "cambria",
  "stix",
  "palatino",
  "helvetica",
];

function argument(name: string) {
  const prefix = `--${name}=`;
  return process.argv.find((value) => value.startsWith(prefix))?.slice(prefix.length);
}

function finitePositive(value: number, label: string) {
  if (!Number.isFinite(value) || value <= 0) {
    throw new Error(`${label} must be a positive finite number.`);
  }
  return value;
}

function safeFileStem(value: string) {
  return value.replace(/[^a-z0-9_-]+/gi, "-").replace(/^-+|-+$/g, "") || "formula";
}

async function main() {
  const outputArgument = argument("output");
  if (!outputArgument) {
    throw new Error(
      "Usage: tsx scripts/generate_word_inline_baseline_fixtures.mts --output=<directory> --suite=structures|sizes|fonts",
    );
  }
  const outputRoot = resolve(outputArgument);
  const suite = argument("suite") ?? "structures";
  await rm(outputRoot, { recursive: true, force: true });
  await mkdir(outputRoot, { recursive: true });

  const anchorLatex = String.raw`x`;
  const items: FixtureItem[] = [];
  const append = async (
    formula: FixtureDefinition,
    fontSizePt: number,
    formulaLetterFont: FormulaLetterFont,
  ) => {
    // Word's MathML importer can collapse a bare mspace generated by \qquad.
    // A mathematical phantom preserves a wide, ink-free separation in both
    // MathJax and OMML, so the rightmost x remains an independent baseline probe.
    const anchoredLatex = `${formula.latex}\\hphantom{I}${anchorLatex}`;
    const exported = latexToSvg(anchoredLatex, {
      displayMode: false,
      fontSizePt: finitePositive(fontSizePt, "fontSizePt"),
      paddingPx: 1,
      background: "transparent",
      formulaLetterFont,
      formulaChineseFont: "system",
    });
    const index = items.length + 1;
    const stem = `${String(index).padStart(3, "0")}-${safeFileStem(formula.name)}-${fontSizePt}pt-${formulaLetterFont}`;
    const svgPath = resolve(outputRoot, `${stem}.svg`);
    await writeFile(svgPath, exported.svg, "utf8");
    const anchorOnlyComparison = suite === "sizes" && fontSizePt >= 42;
    items.push({
      name: `${formula.name}-${fontSizePt}pt-${formulaLetterFont}`,
      latex: anchoredLatex,
      svgPath,
      width: exported.width,
      height: exported.height,
      baseline: exported.baseline,
      mathMl: latexToMathMl(
        anchorOnlyComparison ? anchorLatex : anchoredLatex,
        false,
      ),
      anchorMathMl: "",
      fontSizePt,
      formulaLetterFont,
      ommlFormulaLetterFont: suite === "fonts" ? "katex" : formulaLetterFont,
      formulaChineseFont: "system",
      safetyPaddingPixels: 1,
      comparisonMode: anchorOnlyComparison ? "anchor-only" : "full-formula",
      compactLine: suite === "sizes" && fontSizePt >= 72,
    });
  };

  if (suite === "structures") {
    const fontSizePt = Number(argument("font-size") ?? 10.5);
    const requestedLetterFont = (argument("formula-letter-font") ?? "katex") as FormulaLetterFont;
    if (!allFontChoices.includes(requestedLetterFont)) {
      throw new Error(`Unknown formula-letter-font '${requestedLetterFont}'.`);
    }
    for (const formula of structureFormulas) {
      await append(formula, fontSizePt, requestedLetterFont);
    }
  } else if (suite === "sizes") {
    const sizes = [8, 10.5, 12, 14, 18, 24, 42, 72];
    for (const fontSizePt of sizes) {
      for (const formula of sizeFormulas) {
        await append(formula, fontSizePt, "katex");
      }
    }
  } else if (suite === "fonts") {
    const sizes = [10.5, 24];
    for (const formulaLetterFont of allFontChoices) {
      for (const fontSizePt of sizes) {
        for (const formula of fontFormulas) {
          await append(formula, fontSizePt, formulaLetterFont);
        }
      }
    }
  } else {
    throw new Error(`Unknown fixture suite '${suite}'.`);
  }

  const requestedStart = Number(argument("start") ?? 0);
  const requestedCount = argument("count");
  if (!Number.isInteger(requestedStart) || requestedStart < 0) {
    throw new Error("start must be a non-negative integer.");
  }
  const count = requestedCount === undefined
    ? items.length - requestedStart
    : Number(requestedCount);
  if (!Number.isInteger(count) || count < 1) {
    throw new Error("count must be a positive integer.");
  }
  const selectedItems = items.slice(requestedStart, requestedStart + count);
  if (selectedItems.length === 0) {
    throw new Error("The requested fixture slice is empty.");
  }

  const manifestPath = resolve(outputRoot, "manifest.json");
  await writeFile(
    manifestPath,
    `${JSON.stringify({ root: outputRoot, suite, items: selectedItems }, null, 2)}\n`,
    "utf8",
  );
  console.log(manifestPath);
}

await main();
