// Every foreground string on the landing page. Each is drawn as brush lettering at build time,
// so editing copy means re-running `npm run build:landing-art`.
// `display: true` uses the display script (Norican) for English; `enTex` renders the English side
// with MathJax (Computer Modern) instead, for LaTeX-style card labels; `tex` renders both sides
// with MathJax (for strings that read the same in both languages).
export const copy = {
  navEditor: { zh: "编辑器", en: "Editor" },
  navFeatures: { zh: "功能", en: "Features" },
  navDownload: { zh: "下载", en: "Download" },
  langSwitch: { zh: "EN", en: "中文" },
  refFig: { tex: String.raw`\text{(1)}` },
  refProp: { tex: String.raw`\text{(2)}` },
  refThm: { tex: String.raw`\text{(3)}` },

  heroOpen: { zh: "在浏览器里打开", en: "Open in the browser" },
  heroDownload: { zh: "下载桌面版", en: "Get the desktop app" },
  noteHero: { zh: "无需安装，打开就能写", en: "no install, just start writing" },
  noteFigure: { zh: "你只管写公式，源码自己长出来", en: "you write the maths, the LaTeX writes itself" },
  noteDownload: { zh: "已经替你挑好了", en: "already picked for your machine" },

  say1: { zh: "所见即所得", en: "What you see is what you write.", display: true },
  say2: { zh: "不必再看嵌套格式", en: "No more counting braces.", display: true },
  say3: { zh: "写一次，到处都能用", en: "Write it once, use it anywhere.", display: true },

  figLabel: { zh: "图 1 · 网页编辑器", enTex: String.raw`\textbf{Figure 1}\ \ \text{The web editor.}` },
  figView: { zh: "所见", enTex: String.raw`\Phi\ \ \textit{what you see}` },
  figSource: { zh: "源码", enTex: String.raw`\Lambda\ \ \textit{what LaTeX gets}` },
  figKeys: { zh: "按键", enTex: String.raw`\text{keystrokes}` },
  figBraces: { zh: "源码里的括号", enTex: String.raw`\text{braces in the source}` },
  figTyped: { zh: "你打的括号", enTex: String.raw`\text{braces you typed}` },
  openEditor: { zh: "打开编辑器", en: "Open the editor" },

  propLabel: { zh: "命题 2 · 它能做什么", enTex: String.raw`\textbf{Proposition 2}\ \ \text{(What it does).}` },
  feature1: { zh: "可视化编辑，LaTeX 源码实时同步", en: "Visual editing, with the LaTeX source in sync" },
  feature2: { zh: "拍下手写或截图，识别成公式", en: "Photograph handwriting or a screenshot, get the formula" },
  feature3: { zh: "一键插入 Word 与 PowerPoint", en: "Insert into Word and PowerPoint in one step" },
  feature4: { zh: "原生 MathType 公式，无需安装 MathType", en: "Native MathType equations, no MathType install" },
  feature5: { zh: "导出 LaTeX、SVG 与 PNG", en: "Export LaTeX, SVG and PNG" },
  desktopTag: { zh: "桌面版", en: "desktop" },

  thmLabel: { zh: "定理 3 · 下载", enTex: String.raw`\textbf{Theorem 3}\ \ \text{(Download).}` },
  proofHead: { zh: "证明", enTex: String.raw`\textit{Proof.}` },
  proofMac: { zh: "你的浏览器说这是一台 Apple Silicon 的 Mac。", enTex: String.raw`\text{Your browser reports a Mac with Apple Silicon.}` },
  proofWin: { zh: "你的浏览器说这是一台 Windows 电脑。", enTex: String.raw`\text{Your browser reports a Windows PC.}` },
  proofMobile: { zh: "你在用手机或平板，安装包请到电脑上下载。", enTex: String.raw`\text{You are on a phone or tablet; download on a computer.}` },
  proofOther: { zh: "没能认出你的系统，从下面两种里选一个。", enTex: String.raw`\text{We could not tell your system; pick one below.}` },
  proofCase: { zh: "要离线识别取情形 1，否则情形 2 小得多。", enTex: String.raw`\text{Offline OCR wanted: Case 1. Otherwise Case 2 is far smaller.}` },
  macName: { zh: "macOS", en: "macOS" },
  winName: { zh: "Windows", en: "Windows" },
  macMeta: { zh: "Apple Silicon · macOS 11+ · v{VERSION}", en: "Apple Silicon · macOS 11+ · v{VERSION}" },
  winMeta: { zh: "Windows 10 / 11 · x64 · v{VERSION}", en: "Windows 10 / 11 · x64 · v{VERSION}" },
  thisDevice: { zh: "当前设备", en: "This device" },
  caseFull: { zh: "情形 1 · 完整版，含离线识别", enTex: String.raw`\textit{Case 1.}\ \text{Full, with offline OCR}` },
  caseLite: { zh: "情形 2 · 轻量版，在线识别", enTex: String.raw`\textit{Case 2.}\ \text{Lite, online OCR}` },
  macFullBtn: { zh: "下载 676 MB", en: "Download 676 MB" },
  macLiteBtn: { zh: "下载 12 MB", en: "Download 12 MB" },
  winFullBtn: { zh: "下载 347 MB", en: "Download 347 MB" },
  winLiteBtn: { zh: "下载 120 MB", en: "Download 120 MB" },
  tabLabel: { zh: "表 1 · 离线识别模型（Windows）", enTex: String.raw`\textbf{Table 1}\ \ \text{Offline OCR models (Windows).}` },
  thModel: { zh: "模型", enTex: String.raw`\text{Model}` },
  thSize: { zh: "大小", enTex: String.raw`\text{Size}` },
  thFor: { zh: "适合", enTex: String.raw`\text{Best for}` },
  ocrS: { tex: String.raw`\text{OCR-S}` },
  ocrM: { tex: String.raw`\text{OCR-M}^{\dagger}` },
  ocrL: { tex: String.raw`\text{OCR-L}` },
  ocrSSize: { tex: String.raw`\text{200 MB}` },
  ocrMSize: { tex: String.raw`\text{426 MB}` },
  ocrLSize: { tex: String.raw`\text{670 MB}` },
  ocrSFor: { zh: "最快，日常够用", enTex: String.raw`\text{fastest; fine for everyday use}` },
  ocrMFor: { zh: "又快又准", enTex: String.raw`\text{balanced speed and accuracy}` },
  ocrLFor: { zh: "最准，适合潦草手写", enTex: String.raw`\text{most accurate; messy handwriting}` },
  tabNote: { zh: "† 不确定就选 M", enTex: String.raw`{}^{\dagger}\,\text{Not sure? Take M.}` },
  allReleases: { zh: "全部版本", en: "All releases" },

  remLabel: { zh: "注 4 · 支持", enTex: String.raw`\textbf{Remark 4}\ \ \text{(Support).}` },
  qrWechat: { zh: "微信打赏", en: "WeChat Pay" },
  qrAlipay: { zh: "支付宝打赏", en: "Alipay" },
  qrGroup: { zh: "QQ 交流群", en: "QQ group" },
  qrFailed: { zh: "二维码暂时未能加载。", en: "The QR codes could not be loaded." },
  tips: { zh: "自愿打赏，不影响任何功能。", en: "Tips are optional and never unlock features." },
  group: { zh: "QQ 群 1045801770", en: "QQ group 1045801770" },

  footerName: { zh: "VisualTeX", en: "VisualTeX" },
  footerGithub: { zh: "GitHub", en: "GitHub" },
};
