// Background notebook for the landing page: English-only notes and formulas (field theory,
// measure theory, stochastic calculus). Rendered once by MathJax at build time.
const T = (s) => `\\text{${s}}`;
const R = String.raw;

// Notes are placed once each; `pin` fixes a note in the hero (canvas units, 1600 wide).
export const notes = [
  { size: 36, pin: [-46, 70], src: R`\begin{array}{l}${T("Every symbol you see")}\\ ${T("is a command you")}\\ ${T("no longer type.")}\end{array}` },
  { size: 22, pin: [560, 40], src: R`\begin{array}{c}${T("The nature of the editor")}\\ \scriptstyle ${T("— a bijection —")}\end{array}` },
  { size: 25, pin: [500, 130], src: R`\begin{aligned}\mathcal{V} &: \Lambda \longrightarrow \Phi\\ \mathcal{V}^{-1} &: \Phi \longrightarrow \Lambda\\ \mathcal{V}^{-1}\!\circ\mathcal{V} &= \mathrm{id}_{\Lambda}\end{aligned}` },
  { size: 17, src: R`\begin{array}{rcl}\Lambda &:& ${T("source")}\\ \Phi &:& ${T("form")}\\ \mathcal{V} &:& ${T("the editor")}\\ \sigma &:& ${T("selection")}\\ \kappa(t) &:& ${T("keystrokes")}\\ n_{\{\}}(t) &:& ${T("open braces")}\end{array}` },
  { size: 17, box: true, src: R`\begin{array}{l}\qquad\quad${T("Design question")}\\[4pt] ${T("Find ")}\mathcal{V}${T(" that minimizes ")}\int\kappa\,dt\\ ${T("while every meaning is preserved.")}\end{array}` },
  { size: 19, src: R`\begin{array}{l}${T("Not more features,")}\\ ${T("but fewer braces.")}\end{array}` },
  { size: 21, src: R`\begin{aligned}E_{\text{write}} &= \int_0^{T}\!\Big(\kappa(t) + \lambda\,n_{\{\}}(t)\Big)\,dt\\ \lim_{n_{\{\}}\to 0} E_{\text{write}} &= E_{\text{think}}\end{aligned}` },
  { size: 19, src: R`\begin{array}{ccc}\Lambda & \overset{\mathcal{V}}{\longleftrightarrow} & \Phi\\[6pt] \mathtt{\backslash frac\{a\}\{b\}} & \longleftrightarrow & \dfrac{a}{b}\\[6pt] \mathtt{\backslash sqrt\{x\}} & \longleftrightarrow & \sqrt{x}\end{array}` },
  { size: 15, src: R`\begin{array}{c}${T("Source and form are one thought.")}\\ ${T("We keep them in step.")}\end{array}` },
  { size: 15, src: R`\begin{array}{l}${T("Writing is the arrangement of thought.")}\end{array}` },
  ...["Field equations", "Path integral", "Renormalization", "Gauge symmetry", "Measure", "Integration", "Stochastic calculus", "Geometry", "Transport"]
    .map((h) => ({ size: 20, src: R`\begin{array}{l}${T(h)}\end{array}` })),
];

export const formulas = [
  // ---- field theory
  R`\mathcal{L}_{\text{QED}} = \bar\psi\,(i\gamma^{\mu}D_{\mu} - m)\,\psi - \tfrac14 F_{\mu\nu}F^{\mu\nu}`,
  R`D_{\mu} = \partial_{\mu} - i e A_{\mu},\qquad F_{\mu\nu} = \partial_{\mu}A_{\nu} - \partial_{\nu}A_{\mu}`,
  R`\mathcal{L}_{\text{YM}} = -\tfrac14 F^{a}_{\mu\nu}F^{a\,\mu\nu},\qquad F^{a}_{\mu\nu} = \partial_{\mu}A^{a}_{\nu} - \partial_{\nu}A^{a}_{\mu} + g f^{abc}A^{b}_{\mu}A^{c}_{\nu}`,
  R`Z[J] = \int\mathcal{D}\phi\;\exp\Big(i\!\int d^{4}x\,\big(\mathcal{L}[\phi] + J\phi\big)\Big)`,
  R`(\Box + m^{2})\,\phi = 0,\qquad \Box = \partial_{\mu}\partial^{\mu}`,
  R`(i\gamma^{\mu}\partial_{\mu} - m)\,\psi = 0,\qquad \{\gamma^{\mu},\gamma^{\nu}\} = 2\eta^{\mu\nu}`,
  R`\partial_{\mu}j^{\mu} = 0,\qquad j^{\mu} = \frac{\partial\mathcal{L}}{\partial(\partial_{\mu}\phi)}\,\delta\phi`,
  R`S_{\text{EH}} = \frac{1}{16\pi G}\int d^{4}x\,\sqrt{-g}\,\big(R - 2\Lambda\big)`,
  R`D_{F}(x - y) = \int\frac{d^{4}p}{(2\pi)^{4}}\,\frac{i\,e^{-ip\cdot(x-y)}}{p^{2} - m^{2} + i\epsilon}`,
  R`\langle 0|\,T\{\phi(x_1)\cdots\phi(x_n)\}\,|0\rangle = \frac{1}{i^{n}}\,\frac{\delta^{n}Z[J]}{\delta J(x_1)\cdots\delta J(x_n)}\bigg|_{J=0}`,
  R`\Big[M\frac{\partial}{\partial M} + \beta(g)\frac{\partial}{\partial g} + n\,\gamma(g)\Big]\,G^{(n)}(x_1,\dots,x_n;M,g) = 0`,
  R`\beta(g) = -\frac{g^{3}}{16\pi^{2}}\Big(\frac{11}{3}C_{A} - \frac{4}{3}T_{F}\,n_{f}\Big)`,
  R`W[C] = \operatorname{tr}\,\mathcal{P}\exp\Big(i g\oint_{C} A_{\mu}\,dx^{\mu}\Big)`,
  R`S_{\text{CS}} = \frac{k}{4\pi}\int_{M}\operatorname{tr}\Big(A\wedge dA + \tfrac23\,A\wedge A\wedge A\Big)`,
  R`V(\phi) = -\mu^{2}\,\phi^{\dagger}\phi + \lambda\,(\phi^{\dagger}\phi)^{2}`,
  R`\partial_{\mu}j_{5}^{\mu} = \frac{e^{2}}{16\pi^{2}}\,\epsilon^{\mu\nu\rho\sigma}F_{\mu\nu}F_{\rho\sigma}`,
  R`[\phi(\mathbf{x}),\pi(\mathbf{y})] = i\,\delta^{(3)}(\mathbf{x} - \mathbf{y})`,
  R`\phi(x) = \int\frac{d^{3}p}{(2\pi)^{3}}\,\frac{1}{\sqrt{2E_{\mathbf{p}}}}\Big(a_{\mathbf{p}}\,e^{-ip\cdot x} + a^{\dagger}_{\mathbf{p}}\,e^{ip\cdot x}\Big)`,
  R`T^{\mu\nu} = \frac{\partial\mathcal{L}}{\partial(\partial_{\mu}\phi)}\,\partial^{\nu}\phi - \eta^{\mu\nu}\mathcal{L}`,
  R`dF = 0,\qquad d\star F = \star J`,
  R`\Gamma^{\lambda}_{\mu\nu} = \tfrac12\,g^{\lambda\sigma}\big(\partial_{\mu}g_{\nu\sigma} + \partial_{\nu}g_{\mu\sigma} - \partial_{\sigma}g_{\mu\nu}\big)`,
  R`R^{\rho}{}_{\sigma\mu\nu} = \partial_{\mu}\Gamma^{\rho}_{\nu\sigma} - \partial_{\nu}\Gamma^{\rho}_{\mu\sigma} + \Gamma^{\rho}_{\mu\lambda}\Gamma^{\lambda}_{\nu\sigma} - \Gamma^{\rho}_{\nu\lambda}\Gamma^{\lambda}_{\mu\sigma}`,
  R`R_{\mu\nu} - \tfrac12 R\,g_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^{4}}\,T_{\mu\nu}`,
  R`\mathcal{L} = \tfrac12\,\partial_{\mu}\phi\,\partial^{\mu}\phi - \tfrac12 m^{2}\phi^{2} - \frac{\lambda}{4!}\,\phi^{4}`,
  R`i\mathcal{M} = (-ie)^{2}\,\bar u(p')\gamma^{\mu}u(p)\,\frac{-i g_{\mu\nu}}{q^{2}}\,\bar u(k')\gamma^{\nu}u(k)`,
  R`Z = \operatorname{Tr}\,e^{-\beta H} = \int\mathcal{D}\phi\;e^{-S_{E}[\phi]}`,
  R`\delta_{B}A^{a}_{\mu} = D_{\mu}c^{a},\qquad \delta_{B}c^{a} = -\tfrac{g}{2}\,f^{abc}c^{b}c^{c}`,
  R`\Gamma[\phi_{\text{cl}}] = S[\phi_{\text{cl}}] + \frac{i\hbar}{2}\operatorname{Tr}\log\frac{\delta^{2}S}{\delta\phi\,\delta\phi} + O(\hbar^{2})`,
  R`q_{\mu}\,\mathcal{M}^{\mu}(q) = 0`,
  R`\nabla\cdot\mathbf{E} = \frac{\rho}{\varepsilon_{0}},\qquad \nabla\times\mathbf{B} = \mu_{0}\mathbf{J} + \mu_{0}\varepsilon_{0}\,\frac{\partial\mathbf{E}}{\partial t}`,
  R`i\hbar\,\frac{\partial\Psi}{\partial t} = \Big(-\frac{\hbar^{2}}{2m}\nabla^{2} + V\Big)\Psi`,
  R`\rho\Big(\frac{\partial\mathbf{u}}{\partial t} + \mathbf{u}\cdot\nabla\mathbf{u}\Big) = -\nabla p + \mu\nabla^{2}\mathbf{u} + \mathbf{f}`,
  R`\langle x_f|\,e^{-iHT/\hbar}\,|x_i\rangle = \int\mathcal{D}x(t)\;e^{\frac{i}{\hbar}\int_0^{T}\!L(x,\dot x)\,dt}`,
  R`\mathcal{L}_{\text{SM}} \supset -\tfrac14 G^{a}_{\mu\nu}G^{a\mu\nu} + \bar q\,i\gamma^{\mu}D_{\mu}q + |D_{\mu}H|^{2} - V(H) - y\,\bar Q H q`,
  // ---- measure, integration, probability
  R`\Omega\in\mathcal{F},\quad A\in\mathcal{F}\Rightarrow A^{c}\in\mathcal{F},\quad A_{n}\in\mathcal{F}\Rightarrow\bigcup_{n}A_{n}\in\mathcal{F}`,
  R`\mu\Big(\bigsqcup_{n=1}^{\infty}A_{n}\Big) = \sum_{n=1}^{\infty}\mu(A_{n})`,
  R`\mu^{*}(E) = \inf\Big\{\sum_{k}\lambda(I_{k}) : E\subseteq\bigcup_{k}I_{k}\Big\}`,
  R`\mu^{*}(A) = \mu^{*}(A\cap E) + \mu^{*}(A\cap E^{c})\qquad\forall A\subseteq X`,
  R`\int_{X}f\,d\mu = \sup\Big\{\int_{X}s\,d\mu : 0\le s\le f,\ s\ \text{simple}\Big\}`,
  R`\nu\ll\mu\ \Longrightarrow\ \nu(A) = \int_{A}\frac{d\nu}{d\mu}\,d\mu`,
  R`\int_{X\times Y}f\,d(\mu\otimes\nu) = \int_{X}\Big(\int_{Y}f(x,y)\,d\nu(y)\Big)\,d\mu(x)`,
  R`|f_{n}|\le g\in L^{1},\ \ f_{n}\to f\ \text{a.e.}\ \Longrightarrow\ \lim_{n\to\infty}\int f_{n}\,d\mu = \int f\,d\mu`,
  R`\int\liminf_{n\to\infty}f_{n}\,d\mu\ \le\ \liminf_{n\to\infty}\int f_{n}\,d\mu`,
  R`\|f\|_{L^{p}(\mu)} = \Big(\int_{X}|f|^{p}\,d\mu\Big)^{1/p}`,
  R`\|fg\|_{1}\le\|f\|_{p}\,\|g\|_{q},\qquad \frac1p + \frac1q = 1`,
  R`\mathcal{H}^{s}(E) = \lim_{\delta\to 0}\,\inf\Big\{\sum_{i}(\operatorname{diam}U_{i})^{s} : E\subseteq\bigcup_{i}U_{i},\ \operatorname{diam}U_{i}<\delta\Big\}`,
  R`\dim_{H}E = \inf\{\,s\ge 0 : \mathcal{H}^{s}(E) = 0\,\}`,
  R`\int_{G}f(gx)\,d\mu(x) = \int_{G}f(x)\,d\mu(x)\qquad\forall g\in G`,
  R`\Lambda(f) = \int_{X}f\,d\mu\qquad\forall f\in C_{c}(X)`,
  R`\int_{G}\mathbb{E}[X\mid\mathcal{G}]\,d\mathbb{P} = \int_{G}X\,d\mathbb{P}\qquad\forall G\in\mathcal{G}`,
  R`df(X_{t}) = f'(X_{t})\,dX_{t} + \tfrac12 f''(X_{t})\,d\langle X\rangle_{t}`,
  R`\frac{d\mathbb{Q}}{d\mathbb{P}}\bigg|_{\mathcal{F}_{t}} = \exp\Big(\int_{0}^{t}\theta_{s}\,dW_{s} - \tfrac12\int_{0}^{t}\theta_{s}^{2}\,ds\Big)`,
  R`u(t,x) = \mathbb{E}^{x}\Big[e^{-\int_{0}^{t}V(W_{s})\,ds}\,f(W_{t})\Big]`,
  R`\mathbb{P}\Big(\lim_{n\to\infty}\frac1n\sum_{k=1}^{n}X_{k} = \mathbb{E}X_{1}\Big) = 1`,
  R`\frac{S_{n} - n\mu}{\sigma\sqrt{n}}\ \overset{d}{\longrightarrow}\ \mathcal{N}(0,1)`,
  R`\lambda^{n}\big(T(E)\big) = |\det T|\;\lambda^{n}(E)`,
  R`\int_{\mathbb{R}^{n}}f\circ\Phi\;|\det D\Phi|\,d\lambda = \int_{\Phi(\mathbb{R}^{n})}f\,d\lambda`,
  R`\mu_{n}\Rightarrow\mu\iff\int\varphi\,d\mu_{n}\to\int\varphi\,d\mu\quad\forall\varphi\in C_{b}`,
  R`D_{\mathrm{KL}}(\mu\,\|\,\nu) = \int\log\frac{d\mu}{d\nu}\,d\mu`,
  R`W_{p}(\mu,\nu) = \Big(\inf_{\gamma\in\Gamma(\mu,\nu)}\int|x - y|^{p}\,d\gamma(x,y)\Big)^{1/p}`,
  R`\hat\mu(\xi) = \int_{\mathbb{R}^{n}}e^{-2\pi i\langle x,\xi\rangle}\,d\mu(x)`,
  R`\lim_{r\to 0}\frac{1}{\lambda(B_{r}(x))}\int_{B_{r}(x)}f\,d\lambda = f(x)\quad\text{a.e.}`,
  R`\int_{M}d\omega = \int_{\partial M}\omega`,
  R`\mathbb{E}\Big[\Big(\int_{0}^{t}H_{s}\,dW_{s}\Big)^{2}\Big] = \mathbb{E}\int_{0}^{t}H_{s}^{2}\,ds`,
  R`\frac{\partial p}{\partial t} = -\nabla\cdot(\mathbf{b}\,p) + \tfrac12\,\nabla^{2}\!:\!(\sigma\sigma^{\top}p)`,
  R`\mathbb{P}\big(\sup_{s\le t}|M_{s}|\ge\lambda\big)\le\frac{\mathbb{E}|M_{t}|^{p}}{\lambda^{p}}`,
  R`\int_{-\infty}^{\infty}e^{-x^{2}}\,dx = \sqrt{\pi},\qquad \hat f(\xi) = \int f(x)\,e^{-2\pi i x\xi}\,dx`,
  R`\zeta(s) = \sum_{n=1}^{\infty}\frac{1}{n^{s}} = \prod_{p}\frac{1}{1 - p^{-s}}`,
  R`f(z_0) = \frac{1}{2\pi i}\oint_{\gamma}\frac{f(z)}{z - z_0}\,dz`,
];
