import type { CommandCategory, LatexCommand } from "../types/command";

const makeCommand = (
  id: string,
  command: string,
  insertTemplate: string,
  previewLatex: string,
  labelZh: string,
  labelEn: string,
  category: CommandCategory,
  defaultPriority = 72,
  aliases: string[] = [],
  keywords: string[] = [],
): LatexCommand => ({
  id,
  command,
  insertTemplate,
  previewLatex,
  labelZh,
  labelEn,
  aliases,
  keywords,
  category,
  defaultPriority,
  supportedInMathMode: true,
});

const complexCommands: LatexCommand[] = [
  // 对现有选区添加上标、下标或上下限
  makeCommand("scripts", "_{}^{}", "\\placeholder{}_{\\placeholder{}}^{\\placeholder{}}", "X_{a}^{b}", "添加上下标", "Add upper/lower limits", "structure", 96, ["limits", "scripts"], ["上下限", "上下标"]),
  makeCommand("lower-script", "_{}", "\\placeholder{}_{\\placeholder{}}", "X_{a}", "添加下标", "Add lower limit", "structure", 92, ["lower limit", "subscript"], ["下限", "下标"]),
  makeCommand("upper-script", "^{}", "\\placeholder{}^{\\placeholder{}}", "X^{b}", "添加上标", "Add upper limit", "structure", 92, ["upper limit", "superscript"], ["上限", "上标"]),

  // 基础结构
  makeCommand("smallfrac", "\\tfrac", "\\tfrac{\\placeholder{}}{\\placeholder{}}", "\\tfrac{a}{b}", "行内分式", "Text fraction", "structure", 79, ["tfrac"], ["小分式"]),
  makeCommand("displayfrac", "\\dfrac", "\\dfrac{\\placeholder{}}{\\placeholder{}}", "\\dfrac{a}{b}", "大型分式", "Display fraction", "structure", 78, ["dfrac"], ["大分式"]),
  makeCommand("brackets", "\\left[", "\\left[\\placeholder{}\\right]", "\\left[x\\right]", "方括号", "Brackets", "structure", 81, ["square brackets"], ["方括号"]),
  makeCommand("braces", "\\left\\{", "\\left\\{\\placeholder{}\\right\\}", "\\left\\{x\\right\\}", "花括号", "Braces", "structure", 80, ["curly braces"], ["大括号", "花括号"]),
  makeCommand("anglebrackets", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle x\\rangle", "尖括号", "Angle brackets", "structure", 77, ["angle brackets"], ["尖括号"]),
  makeCommand("floor", "\\lfloor", "\\left\\lfloor\\placeholder{}\\right\\rfloor", "\\lfloor x\\rfloor", "下取整", "Floor", "structure", 76, ["floor"], ["向下取整"]),
  makeCommand("ceil", "\\lceil", "\\left\\lceil\\placeholder{}\\right\\rceil", "\\lceil x\\rceil", "上取整", "Ceiling", "structure", 76, ["ceil", "ceiling"], ["向上取整"]),
  makeCommand("overline", "\\overline", "\\overline{\\placeholder{}}", "\\overline{x}", "上划线", "Overline", "structure", 75, ["bar", "overline"], ["平均值", "上划线"]),
  makeCommand("hat", "\\hat", "\\hat{\\placeholder{}}", "\\hat{x}", "帽子重音", "Hat accent", "structure", 84, ["hat"], ["帽子", "重音"]),
  makeCommand("widehat", "\\widehat", "\\widehat{\\placeholder{}}", "\\widehat{ABC}", "宽帽子重音", "Wide hat", "structure", 78, ["wide hat"], ["宽帽子", "重音"]),
  makeCommand("tilde", "\\tilde", "\\tilde{\\placeholder{}}", "\\tilde{x}", "波浪重音", "Tilde accent", "structure", 83, ["tilde"], ["波浪号", "重音"]),
  makeCommand("widetilde", "\\widetilde", "\\widetilde{\\placeholder{}}", "\\widetilde{ABC}", "宽波浪重音", "Wide tilde", "structure", 77, ["wide tilde"], ["宽波浪号", "重音"]),
  makeCommand("dotaccent", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "点重音", "Dot accent", "structure", 80, ["dot"], ["点重音"]),
  makeCommand("ddotaccent", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "双点重音", "Double-dot accent", "structure", 79, ["double dot", "ddot"], ["双点重音"]),
  makeCommand("checkaccent", "\\check", "\\check{\\placeholder{}}", "\\check{x}", "倒帽重音", "Check accent", "structure", 73, ["check accent"], ["倒帽", "重音"]),
  makeCommand("breveaccent", "\\breve", "\\breve{\\placeholder{}}", "\\breve{x}", "短音重音", "Breve accent", "structure", 72, ["breve"], ["短音", "重音"]),
  makeCommand("acuteaccent", "\\acute", "\\acute{\\placeholder{}}", "\\acute{x}", "尖音重音", "Acute accent", "structure", 71, ["acute"], ["尖音", "重音"]),
  makeCommand("graveaccent", "\\grave", "\\grave{\\placeholder{}}", "\\grave{x}", "重音符", "Grave accent", "structure", 70, ["grave"], ["重音符"]),
  makeCommand("ringaccent", "\\mathring", "\\mathring{\\placeholder{}}", "\\mathring{x}", "圆圈重音", "Ring accent", "structure", 69, ["ring accent"], ["圆圈", "重音"]),
  makeCommand("overrightarrow", "\\overrightarrow", "\\overrightarrow{\\placeholder{}}", "\\overrightarrow{AB}", "上方右箭头", "Over-arrow right", "structure", 77, ["over arrow"], ["向量箭头"]),
  makeCommand("overleftarrow", "\\overleftarrow", "\\overleftarrow{\\placeholder{}}", "\\overleftarrow{AB}", "上方左箭头", "Over-arrow left", "structure", 74, ["over left arrow"], ["向量箭头"]),
  makeCommand("underline", "\\underline", "\\underline{\\placeholder{}}", "\\underline{x}", "下划线", "Underline", "structure", 73, ["underline"], ["下划线"]),
  makeCommand("overbrace", "\\overbrace", "\\overbrace{\\placeholder{}}^{\\placeholder{}}", "\\overbrace{a+\\cdots+a}^{n}", "上花括号", "Overbrace", "structure", 72, ["overbrace"], ["上括注"]),
  makeCommand("underbrace", "\\underbrace", "\\underbrace{\\placeholder{}}_{\\placeholder{}}", "\\underbrace{a+\\cdots+a}_{n}", "下花括号", "Underbrace", "structure", 72, ["underbrace"], ["下括注"]),
  makeCommand("cases", "\\begin{cases}", "\\begin{cases}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{cases}", "f(x)=\\begin{cases}x&x>0\\\\0&x\\leq0\\end{cases}", "分段函数", "Cases", "structure", 85, ["cases", "piecewise"], ["分段函数"]),
  makeCommand("boxed", "\\boxed", "\\boxed{\\placeholder{}}", "\\boxed{x}", "方框公式", "Boxed", "structure", 70, ["boxed", "box"], ["方框"]),
  makeCommand("left-parenthesis-only", "\\left(", "\\left(\\placeholder{}\\right.", "\\left(x\\right.", "仅左圆括号", "Left parenthesis only", "structure", 68, ["left parenthesis"], ["单边括号", "左括号"]),
  makeCommand("right-parenthesis-only", "\\right)", "\\left.\\placeholder{}\\right)", "\\left.x\\right)", "仅右圆括号", "Right parenthesis only", "structure", 68, ["right parenthesis"], ["单边括号", "右括号"]),
  makeCommand("left-bracket-only", "\\left[", "\\left[\\placeholder{}\\right.", "\\left[x\\right.", "仅左方括号", "Left bracket only", "structure", 67, ["left bracket"], ["单边方括号"]),
  makeCommand("right-bracket-only", "\\right]", "\\left.\\placeholder{}\\right]", "\\left.x\\right]", "仅右方括号", "Right bracket only", "structure", 67, ["right bracket"], ["单边方括号"]),
  makeCommand("left-brace-only", "\\left\\{", "\\left\\{\\placeholder{}\\right.", "\\left\\{x\\right.", "仅左花括号", "Left brace only", "structure", 67, ["left brace"], ["单边花括号"]),
  makeCommand("right-brace-only", "\\right\\}", "\\left.\\placeholder{}\\right\\}", "\\left.x\\right\\}", "仅右花括号", "Right brace only", "structure", 67, ["right brace"], ["单边花括号"]),
  makeCommand("mixed-paren-bracket", "(]", "\\left(\\placeholder{}\\right]", "\\left(x\\right]", "圆方混合括号", "Parenthesis-bracket pair", "structure", 66, ["mixed delimiter"], ["混合括号"]),
  makeCommand("mixed-bracket-paren", "[)", "\\left[\\placeholder{}\\right)", "\\left[x\\right)", "方圆混合括号", "Bracket-parenthesis pair", "structure", 66, ["mixed delimiter"], ["混合括号"]),
  makeCommand("double-brackets", "[[ ]]", "\\left[\\!\\left[\\placeholder{}\\right]\\!\\right]", "\\left[\\!\\left[x\\right]\\!\\right]", "双层方括号", "Double brackets", "structure", 65, ["double brackets"], ["双括号"]),
  makeCommand("moustache-pair", "\\lmoustache", "\\left\\lmoustache\\placeholder{}\\right\\rmoustache", "\\left\\lmoustache x\\right\\rmoustache", "八字括号", "Moustache delimiters", "structure", 62, ["moustache"], ["特殊括号"]),
  makeCommand("corner-pair", "\\ulcorner", "\\left\\ulcorner\\placeholder{}\\right\\urcorner", "\\left\\ulcorner x\\right\\urcorner", "上角括号", "Upper corner delimiters", "structure", 61, ["corner delimiters"], ["角括号"]),
  makeCommand("baraccent", "\\bar", "\\bar{\\placeholder{}}", "\\bar{x}", "短上划线", "Bar accent", "structure", 78, ["bar accent"], ["短横线", "重音"]),
  makeCommand("vecaccent", "\\vec", "\\vec{\\placeholder{}}", "\\vec{x}", "向量箭头重音", "Vector accent", "structure", 81, ["vector accent"], ["向量", "重音"]),
  makeCommand("dddotaccent", "\\dddot", "\\dddot{\\placeholder{}}", "\\dddot{x}", "三点重音", "Triple-dot accent", "structure", 68, ["triple dot"], ["三点重音"]),
  makeCommand("ddddotaccent", "\\ddddot", "\\ddddot{\\placeholder{}}", "\\ddddot{x}", "四点重音", "Quadruple-dot accent", "structure", 67, ["quadruple dot"], ["四点重音"]),
  makeCommand("cases-three", "\\begin{cases}", "\\begin{cases}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{cases}", "f(x)=\\begin{cases}a&x<0\\\\b&x=0\\\\c&x>0\\end{cases}", "三行分段函数", "Three-row cases", "structure", 83, ["three cases"], ["三行分段函数"]),

  // 微积分与常用函数
  makeCommand("intplain", "\\int", "\\int \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\int f(x)\\,\\mathrm{d}x", "不定积分", "Indefinite integral", "calculus", 99, ["indefinite integral", "integral"], ["不定积分", "积分"]),
  makeCommand("iint-bounds", "\\iint", "\\iint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}A", "\\iint_D^S f\\,\\mathrm{d}A", "带上下限二重积分", "Bounded double integral", "calculus", 91, ["bounded double integral"], ["二重积分", "上下限"]),
  makeCommand("iiint-bounds", "\\iiint", "\\iiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V^W f\\,\\mathrm{d}V", "带上下限三重积分", "Bounded triple integral", "calculus", 90, ["bounded triple integral"], ["三重积分", "上下限"]),
  makeCommand("oint-bounds", "\\oint", "\\oint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\oint_C^D f\\,\\mathrm{d}s", "带上下限环路积分", "Bounded contour integral", "calculus", 89, ["bounded contour integral"], ["环路积分", "上下限"]),
  makeCommand("sum-finite", "\\sum", "\\sum_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\sum_{k=1}^{n}a_k", "有限求和", "Finite sum", "calculus", 98, ["finite sum"], ["有限求和", "上下限"]),
  makeCommand("prod-finite", "\\prod", "\\prod_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\prod_{k=1}^{n}a_k", "有限连乘", "Finite product", "calculus", 92, ["finite product"], ["有限连乘", "上下限"]),
  makeCommand("lineintegral", "\\int", "\\int_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}s", "\\int_C f\\,\\mathrm{d}s", "曲线积分", "Line integral", "calculus", 96, ["line integral", "path integral"], ["曲线积分", "线积分"]),
  makeCommand("surfaceintegral", "\\iint", "\\iint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\iint_S f\\,\\mathrm{d}S", "曲面积分", "Surface integral", "calculus", 95, ["surface integral", "double integral"], ["曲面积分", "面积分", "二重积分"]),
  makeCommand("iiint", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "三重积分", "Triple integral", "calculus", 94, ["triple integral"], ["三重积分"]),
  makeCommand("volumeintegral", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "体积分", "Volume integral", "calculus", 93, ["volume integral"], ["体积分"]),
  makeCommand("closed-surface-integral", "\\oiint", "\\oiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\oiint_S \\mathbf{F}\\cdot\\mathrm{d}\\mathbf{S}", "闭合曲面积分", "Closed surface integral", "calculus", 92, ["closed surface integral", "oiint"], ["闭合曲面积分", "闭合面积分"]),
  makeCommand("closed-volume-integral", "\\oiiint", "\\oiiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\oiiint_V f\\,\\mathrm{d}V", "闭合体积分", "Closed volume integral", "calculus", 87, ["closed volume integral", "oiiint"], ["闭合体积分"]),

  makeCommand("derivative", "\\frac{d}{dx}", "\\frac{\\mathrm{d}\\placeholder{}}{\\mathrm{d}\\placeholder{}}", "\\frac{\\mathrm{d}f}{\\mathrm{d}x}", "导数", "Derivative", "calculus", 91, ["derivative"], ["导数", "微分"]),
  makeCommand("secondderivative", "\\frac{d^2}{dx^2}", "\\frac{\\mathrm{d}^{2}\\placeholder{}}{\\mathrm{d}\\placeholder{}^{2}}", "\\frac{\\mathrm{d}^{2}f}{\\mathrm{d}x^{2}}", "二阶导数", "Second derivative", "calculus", 83, ["second derivative"], ["二阶导数"]),
  makeCommand("partialsecond", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}^{2}}", "\\frac{\\partial^{2}f}{\\partial x^{2}}", "二阶偏导", "Second partial", "calculus", 82, ["second partial"], ["二阶偏导"]),
  makeCommand("mixedpartial", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}\\partial\\placeholder{}}", "\\frac{\\partial^{2}f}{\\partial x\\partial y}", "混合偏导", "Mixed partial", "calculus", 81, ["mixed partial"], ["混合偏导"]),
  makeCommand("evalbar", "\\left.", "\\left.\\placeholder{}\\right|_{\\placeholder{}}^{\\placeholder{}}", "\\left.F(x)\\right|_a^b", "代入上下限", "Evaluation", "calculus", 80, ["evaluate"], ["代入", "上下限"]),
  makeCommand("series", "\\sum", "\\sum_{\\placeholder{}=0}^{\\infty} \\placeholder{}", "\\sum_{n=0}^{\\infty}a_n", "无穷级数", "Infinite series", "calculus", 97, ["series", "summation"], ["级数", "无穷求和"]),
  makeCommand("productseries", "\\prod", "\\prod_{\\placeholder{}=1}^{\\infty} \\placeholder{}", "\\prod_{n=1}^{\\infty}a_n", "无穷乘积", "Infinite product", "calculus", 94, ["infinite product", "product"], ["无穷乘积", "连乘"]),
  makeCommand("coproduct", "\\coprod", "\\coprod_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\coprod_{i=1}^{n} A_i", "余积", "Coproduct", "calculus", 84, ["coproduct"], ["余积"]),
  makeCommand("bigcap-limits", "\\bigcap", "\\bigcap_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigcap_{i=1}^{n}A_i", "大交集", "Big intersection", "calculus", 88, ["big intersection"], ["大交集", "巨算符"]),
  makeCommand("bigcup-limits", "\\bigcup", "\\bigcup_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigcup_{i=1}^{n}A_i", "大并集", "Big union", "calculus", 88, ["big union"], ["大并集", "巨算符"]),
  makeCommand("bigsqcup-limits", "\\bigsqcup", "\\bigsqcup_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigsqcup_{i=1}^{n}A_i", "大方并", "Big square union", "calculus", 82, ["big square union"], ["方并", "巨算符"]),
  makeCommand("bigvee-limits", "\\bigvee", "\\bigvee_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigvee_{i=1}^{n}P_i", "大逻辑或", "Big logical or", "calculus", 84, ["big vee"], ["大逻辑或", "巨算符"]),
  makeCommand("bigwedge-limits", "\\bigwedge", "\\bigwedge_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigwedge_{i=1}^{n}P_i", "大逻辑与", "Big logical and", "calculus", 84, ["big wedge"], ["大逻辑与", "巨算符"]),
  makeCommand("bigodot-limits", "\\bigodot", "\\bigodot_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigodot_{i=1}^{n}A_i", "大圆点积", "Big circled dot", "calculus", 80, ["big odot"], ["大圆点", "巨算符"]),
  makeCommand("bigoplus-limits", "\\bigoplus", "\\bigoplus_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigoplus_{i=1}^{n}V_i", "大直和", "Big direct sum", "calculus", 86, ["big direct sum"], ["大直和", "巨算符"]),
  makeCommand("bigotimes-limits", "\\bigotimes", "\\bigotimes_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigotimes_{i=1}^{n}V_i", "大张量积", "Big tensor product", "calculus", 86, ["big tensor product"], ["大张量积", "巨算符"]),
  makeCommand("biguplus-limits", "\\biguplus", "\\biguplus_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\biguplus_{i=1}^{n}A_i", "大多重并", "Big multiset union", "calculus", 80, ["big uplus"], ["大多重并", "巨算符"]),
  makeCommand("lim-infty", "\\lim", "\\lim_{\\placeholder{}\\to\\infty} \\placeholder{}", "\\lim_{x\\to\\infty}f(x)", "无穷远极限", "Limit at infinity", "calculus", 95, ["limit infinity"], ["无穷远极限"]),
  makeCommand("lim-left", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{-}} \\placeholder{}", "\\lim_{x\\to a^-}f(x)", "左极限", "Left-hand limit", "calculus", 93, ["left limit"], ["左极限"]),
  makeCommand("lim-right", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{+}} \\placeholder{}", "\\lim_{x\\to a^+}f(x)", "右极限", "Right-hand limit", "calculus", 93, ["right limit"], ["右极限"]),
  makeCommand("log", "\\log", "\\log_{\\placeholder{}}\\left(\\placeholder{}\\right)", "\\log_a x", "对数", "Logarithm", "calculus", 86, ["logarithm"], ["对数"]),
  makeCommand("ln", "\\ln", "\\ln\\left(\\placeholder{}\\right)", "\\ln x", "自然对数", "Natural log", "calculus", 87, ["natural log"], ["自然对数"]),
  makeCommand("exp", "\\exp", "\\exp\\left(\\placeholder{}\\right)", "\\exp(x)", "指数函数", "Exponential", "calculus", 85, ["exponential"], ["指数函数"]),
  makeCommand("sin", "\\sin", "\\sin\\left(\\placeholder{}\\right)", "\\sin x", "正弦", "Sine", "calculus", 89, ["sine"], ["正弦"]),
  makeCommand("cos", "\\cos", "\\cos\\left(\\placeholder{}\\right)", "\\cos x", "余弦", "Cosine", "calculus", 89, ["cosine"], ["余弦"]),
  makeCommand("tan", "\\tan", "\\tan\\left(\\placeholder{}\\right)", "\\tan x", "正切", "Tangent", "calculus", 84, ["tangent"], ["正切"]),
  makeCommand("arcsin", "\\arcsin", "\\arcsin\\left(\\placeholder{}\\right)", "\\arcsin x", "反正弦", "Arcsine", "calculus", 74, ["arcsine"], ["反正弦"]),
  makeCommand("arccos", "\\arccos", "\\arccos\\left(\\placeholder{}\\right)", "\\arccos x", "反余弦", "Arccosine", "calculus", 74, ["arccosine"], ["反余弦"]),
  makeCommand("arctan", "\\arctan", "\\arctan\\left(\\placeholder{}\\right)", "\\arctan x", "反正切", "Arctangent", "calculus", 74, ["arctangent"], ["反正切"]),
  makeCommand("min", "\\min", "\\min_{\\placeholder{}}\\placeholder{}", "\\min_x f(x)", "最小值", "Minimum", "calculus", 78, ["minimum"], ["最小值"]),
  makeCommand("max", "\\max", "\\max_{\\placeholder{}}\\placeholder{}", "\\max_x f(x)", "最大值", "Maximum", "calculus", 78, ["maximum"], ["最大值"]),

  // 矩阵与线性代数
  makeCommand("matrixplain2", "\\begin{matrix}", "\\begin{matrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{matrix}", "\\begin{matrix}a&b\\\\c&d\\end{matrix}", "无括号矩阵", "Plain matrix", "matrix", 82, ["matrix"], ["无括号矩阵"]),
  makeCommand("Bmatrix2", "\\begin{Bmatrix}", "\\begin{Bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Bmatrix}", "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}", "花括号矩阵", "Brace matrix", "matrix", 80, ["Bmatrix"], ["花括号矩阵"]),
  makeCommand("Vmatrix2", "\\begin{Vmatrix}", "\\begin{Vmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Vmatrix}", "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}", "双竖线矩阵", "Double-bar matrix", "matrix", 78, ["Vmatrix"], ["范数矩阵"]),
  makeCommand("rowvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\placeholder{} & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a&b&c\\end{bmatrix}", "行向量", "Row vector", "matrix", 86, ["row vector"], ["行向量"]),
  makeCommand("colvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} \\\\ \\placeholder{} \\\\ \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a\\\\b\\\\c\\end{bmatrix}", "列向量", "Column vector", "matrix", 86, ["column vector"], ["列向量"]),
  makeCommand("det", "\\det", "\\det\\left(\\placeholder{}\\right)", "\\det(A)", "行列式算子", "Determinant operator", "matrix", 82, ["det"], ["行列式算子"]),
  makeCommand("trace", "\\operatorname{tr}", "\\operatorname{tr}\\left(\\placeholder{}\\right)", "\\operatorname{tr}(A)", "迹", "Trace", "matrix", 78, ["trace", "tr"], ["矩阵的迹"]),
  makeCommand("rank", "\\operatorname{rank}", "\\operatorname{rank}\\left(\\placeholder{}\\right)", "\\operatorname{rank}(A)", "秩", "Rank", "matrix", 78, ["rank"], ["矩阵的秩"]),
  makeCommand("norm", "\\lVert", "\\left\\lVert\\placeholder{}\\right\\rVert", "\\lVert\\mathbf{x}\\rVert", "范数", "Norm", "matrix", 81, ["norm"], ["范数"]),
  makeCommand("unitvector", "\\hat", "\\hat{\\mathbf{\\placeholder{}}}", "\\hat{\\mathbf{e}}", "单位矢量", "Unit vector", "matrix", 84, ["unit vector"], ["单位矢量"]),
  makeCommand("matrix-dots", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\cdots & \\placeholder{} \\\\ \\vdots & \\ddots & \\vdots \\\\ \\placeholder{} & \\cdots & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a_{11}&\\cdots&a_{1n}\\\\\\vdots&\\ddots&\\vdots\\\\a_{m1}&\\cdots&a_{mn}\\end{bmatrix}", "省略号矩阵", "Ellipsis matrix", "matrix", 90, ["ellipsis matrix"], ["省略号矩阵", "通用矩阵"]),
  makeCommand("diagonal-matrix", "\\operatorname{diag}", "\\begin{bmatrix}\\placeholder{} & 0 & \\cdots & 0 \\\\ 0 & \\placeholder{} & \\ddots & \\vdots \\\\ \\vdots & \\ddots & \\ddots & 0 \\\\ 0 & \\cdots & 0 & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a_1&0&\\cdots&0\\\\0&a_2&\\ddots&\\vdots\\\\\\vdots&\\ddots&\\ddots&0\\\\0&\\cdots&0&a_n\\end{bmatrix}", "对角矩阵", "Diagonal matrix", "matrix", 88, ["diagonal matrix"], ["对角矩阵"]),
  makeCommand("augmented-matrix", "\\left[", "\\left[\\begin{array}{cc|c}\\placeholder{} & \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} & \\placeholder{}\\end{array}\\right]", "\\left[\\begin{array}{cc|c}1&0&a\\\\0&1&b\\end{array}\\right]", "增广矩阵", "Augmented matrix", "matrix", 87, ["augmented matrix"], ["增广矩阵"]),
  makeCommand("block-matrix", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}A&B\\\\C&D\\end{bmatrix}", "分块矩阵", "Block matrix", "matrix", 85, ["block matrix"], ["分块矩阵"]),

  // 物理常用结构
  makeCommand("expectation", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle A\\rangle", "期望值", "Expectation value", "physics", 90, ["expectation"], ["期望值"]),
  makeCommand("braket", "\\langle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\psi\\rangle", "内积", "Bra-ket", "physics", 92, ["braket", "inner product"], ["内积", "狄拉克"]),
  makeCommand("commutator", "[", "\\left[\\placeholder{},\\placeholder{}\\right]", "[A,B]", "对易子", "Commutator", "physics", 88, ["commutator"], ["对易子"]),
  makeCommand("anticommutator", "\\{", "\\left\\{\\placeholder{},\\placeholder{}\\right\\}", "\\{A,B\\}", "反对易子", "Anticommutator", "physics", 82, ["anticommutator"], ["反对易子"]),
  makeCommand("timederivative", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "时间一阶导", "Time derivative", "physics", 86, ["dot derivative"], ["时间导数"]),
  makeCommand("timesecond", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "时间二阶导", "Second time derivative", "physics", 84, ["double dot"], ["二阶时间导数"]),
  makeCommand("outerproduct", "|\\psi\\rangle\\langle\\phi|", "|\\placeholder{}\\rangle\\langle\\placeholder{}|", "|\\psi\\rangle\\langle\\phi|", "外积", "Outer product", "physics", 91, ["outer product", "ket bra"], ["外积", "狄拉克"]),
  makeCommand("matrixelement", "\\langle\\phi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\hat A|\\psi\\rangle", "矩阵元", "Matrix element", "physics", 90, ["matrix element"], ["矩阵元", "量子力学"]),
  makeCommand("expectation-operator", "\\langle\\psi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\psi|\\hat A|\\psi\\rangle", "算符期望值", "Operator expectation", "physics", 89, ["operator expectation"], ["期望值", "算符"]),

  makeCommand("time-ordering", "\\mathcal{T}", "\\mathcal{T}\\left\\{\\placeholder{}\\right\\}", "\\mathcal{T}\\{A(t)B(t')\\}", "时间序算符", "Time ordering", "physics", 75, ["time ordering"], ["时间序", "量子场论"]),
];

type SimpleDefinition = [
  id: string,
  command: string,
  labelZh: string,
  labelEn: string,
  category: CommandCategory,
  priority?: number,
  aliases?: string[],
  keywords?: string[],
];

const simpleDefinitions: SimpleDefinition[] = [
  // 矩阵
  ["transpose", "^{\\mathsf{T}}", "转置", "Transpose", "matrix", 84, ["transpose"], ["转置"]],
  ["inverse", "^{-1}", "逆矩阵", "Inverse", "matrix", 85, ["inverse"], ["逆矩阵"]],
  ["dotproduct", "\\cdot", "点积", "Dot product", "matrix", 83, ["dot product"], ["点积", "内积"]],
  ["crossproduct", "\\times", "叉积", "Cross product", "matrix", 83, ["cross product"], ["叉积", "外积"]],

  // 二元运算符
  ["plusminus", "\\pm", "正负号", "Plus-minus", "relation", 94],
  ["minusplus", "\\mp", "负正号", "Minus-plus", "relation", 86],
  ["multiply", "\\times", "乘号", "Multiplication", "relation", 94],
  ["division", "\\div", "除号", "Division", "relation", 92],
  ["centerdot", "\\cdot", "居中点乘", "Centered dot", "relation", 90],
  ["asterisk", "\\ast", "星号运算", "Asterisk operator", "relation", 76],
  ["starop", "\\star", "五角星运算", "Star operator", "relation", 74],
  ["circleop", "\\circ", "圆圈运算", "Circle operator", "relation", 78],
  ["bulletop", "\\bullet", "实心点运算", "Bullet operator", "relation", 78],
  ["diamondop", "\\diamond", "菱形运算", "Diamond operator", "relation", 72],
  ["triangleop", "\\triangle", "三角运算符", "Triangle operator", "relation", 70],
  ["triangledownop", "\\triangledown", "倒三角运算符", "Down triangle operator", "relation", 70],
  ["bigtriangleupop", "\\bigtriangleup", "大上三角", "Big triangle up", "relation", 68],
  ["bigtriangledownop", "\\bigtriangledown", "大下三角", "Big triangle down", "relation", 68],
  ["ominus", "\\ominus", "圆圈减", "Circled minus", "relation", 82],
  ["oslash", "\\oslash", "圆圈斜线", "Circled slash", "relation", 78],
  ["odot", "\\odot", "圆圈点", "Circled dot", "relation", 82],
  ["circledast", "\\circledast", "圆圈星号", "Circled asterisk", "relation", 74],
  ["circledcirc", "\\circledcirc", "双圆圈", "Circled circle", "relation", 72],
  ["circleddash", "\\circleddash", "圆圈短横", "Circled dash", "relation", 72],
  ["boxplus", "\\boxplus", "方框加", "Boxed plus", "relation", 76],
  ["boxminus", "\\boxminus", "方框减", "Boxed minus", "relation", 74],
  ["boxtimes", "\\boxtimes", "方框乘", "Boxed times", "relation", 76],
  ["boxdot", "\\boxdot", "方框点", "Boxed dot", "relation", 74],
  ["uplus", "\\uplus", "多重并", "Multiset union", "relation", 76],
  ["sqcap", "\\sqcap", "方形交", "Square intersection", "relation", 74],
  ["sqcup", "\\sqcup", "方形并", "Square union", "relation", 74],
  ["amalg", "\\amalg", "自由积", "Amalgamation", "relation", 66],
  ["wreath", "\\wr", "花环积", "Wreath product", "relation", 64],
  ["divideontimes", "\\divideontimes", "带除线乘号", "Divide on times", "relation", 64],
  ["ltimes", "\\ltimes", "左半直积", "Left semidirect product", "relation", 68],
  ["rtimes", "\\rtimes", "右半直积", "Right semidirect product", "relation", 68],
  ["leftthreetimes", "\\leftthreetimes", "左三叉乘", "Left three-times", "relation", 64],
  ["rightthreetimes", "\\rightthreetimes", "右三叉乘", "Right three-times", "relation", 64],
  ["intercal", "\\intercal", "交错积", "Intercal", "relation", 62],

  // 希腊字母
  ["epsilon", "\\epsilon", "艾普西隆", "Epsilon", "greek", 82],
  ["varepsilon", "\\varepsilon", "变体艾普西隆", "Variant epsilon", "greek", 80],
  ["zeta", "\\zeta", "泽塔", "Zeta", "greek", 78],
  ["eta", "\\eta", "伊塔", "Eta", "greek", 78],
  ["vartheta", "\\vartheta", "变体西塔", "Variant theta", "greek", 78],
  ["iota", "\\iota", "约塔", "Iota", "greek", 76],
  ["kappa", "\\kappa", "卡帕", "Kappa", "greek", 80],
  ["nu", "\\nu", "纽", "Nu", "greek", 79],
  ["xi", "\\xi", "克西", "Xi", "greek", 76],
  ["rho", "\\rho", "柔", "Rho", "greek", 82],
  ["varrho", "\\varrho", "变体柔", "Variant rho", "greek", 72],
  ["tau", "\\tau", "陶", "Tau", "greek", 81],
  ["upsilon", "\\upsilon", "宇普西隆", "Upsilon", "greek", 70],
  ["phi", "\\phi", "斐", "Phi", "greek", 86],
  ["varphi", "\\varphi", "变体斐", "Variant phi", "greek", 84],
  ["chi", "\\chi", "希", "Chi", "greek", 74],
  ["psi", "\\psi", "普赛", "Psi", "greek", 84],
  ["Gamma", "\\Gamma", "大写伽马", "Gamma", "greek", 76],
  ["Delta", "\\Delta", "大写德尔塔", "Delta", "greek", 84],
  ["Theta", "\\Theta", "大写西塔", "Theta", "greek", 72],
  ["Lambda", "\\Lambda", "大写拉姆达", "Lambda", "greek", 76],
  ["Xi", "\\Xi", "大写克西", "Xi", "greek", 68],
  ["Pi", "\\Pi", "大写派", "Pi", "greek", 74],
  ["Sigma", "\\Sigma", "大写西格玛", "Sigma", "greek", 78],
  ["Phi", "\\Phi", "大写斐", "Phi", "greek", 76],
  ["Psi", "\\Psi", "大写普赛", "Psi", "greek", 78],
  ["Omega", "\\Omega", "大写欧米伽", "Omega", "greek", 82],
  ["varpi", "\\varpi", "变体派", "Variant pi", "greek", 73],
  ["varsigma", "\\varsigma", "末尾西格玛", "Final sigma", "greek", 71],
  ["digamma", "\\digamma", "双伽马", "Digamma", "greek", 68],

  // 关系符号
  ["lt", "<", "小于", "Less than", "relation", 92],
  ["gt", ">", "大于", "Greater than", "relation", 92],
  ["equiv", "\\equiv", "恒等于", "Equivalent", "relation", 88],
  ["sim", "\\sim", "相似", "Similar", "relation", 82],
  ["simeq", "\\simeq", "渐近相等", "Asymptotically equal", "relation", 80],
  ["cong", "\\cong", "全等", "Congruent", "relation", 78],
  ["ll", "\\ll", "远小于", "Much less", "relation", 82],
  ["gg", "\\gg", "远大于", "Much greater", "relation", 82],
  ["parallel", "\\parallel", "平行", "Parallel", "relation", 79],
  ["perp", "\\perp", "垂直", "Perpendicular", "relation", 81],
  ["mid", "\\mid", "整除", "Divides", "relation", 74],
  ["nmid", "\\nmid", "不整除", "Does not divide", "relation", 72],
  ["prec", "\\prec", "先于", "Precedes", "relation", 68],
  ["succ", "\\succ", "后于", "Succeeds", "relation", 68],
  ["leqq", "\\leqq", "双线小于等于", "Less than or equal (double)", "relation", 77],
  ["geqq", "\\geqq", "双线大于等于", "Greater than or equal (double)", "relation", 77],
  ["lneq", "\\lneq", "小于但不等于", "Less than but not equal", "relation", 75],
  ["gneq", "\\gneq", "大于但不等于", "Greater than but not equal", "relation", 75],
  ["lesssim", "\\lesssim", "小于或近似", "Less than or similar", "relation", 74],
  ["gtrsim", "\\gtrsim", "大于或近似", "Greater than or similar", "relation", 74],
  ["lessapprox", "\\lessapprox", "小于或约等于", "Less than or approximately equal", "relation", 73],
  ["gtrapprox", "\\gtrapprox", "大于或约等于", "Greater than or approximately equal", "relation", 73],
  ["preceq", "\\preceq", "先于或等于", "Precedes or equals", "relation", 72],
  ["succeq", "\\succeq", "后于或等于", "Succeeds or equals", "relation", 72],
  ["asymp", "\\asymp", "渐近等价", "Asymptotically equivalent", "relation", 76],
  ["doteq", "\\doteq", "点等号", "Dotted equals", "relation", 71],
  ["triangleq", "\\triangleq", "定义等号", "Defined as", "relation", 78],
  ["models", "\\models", "满足", "Models", "relation", 74],
  ["vdash", "\\vdash", "可推出", "Proves", "relation", 73],
  ["dashv", "\\dashv", "反向推出", "Reverse turnstile", "relation", 67],
  ["bowtie", "\\bowtie", "蝴蝶结关系", "Bowtie relation", "relation", 66],
  ["smile", "\\smile", "微笑关系", "Smile relation", "relation", 64],
  ["frown", "\\frown", "皱眉关系", "Frown relation", "relation", 64],
  ["approxeq", "\\approxeq", "近似等于", "Approximately equal", "relation", 78],
  ["eqsim", "\\eqsim", "等价相似", "Equal or similar", "relation", 72],
  ["backsim", "\\backsim", "反向相似", "Reverse similar", "relation", 68],
  ["backsimeq", "\\backsimeq", "反向渐近等于", "Reverse asymptotically equal", "relation", 67],
  ["fallingdotseq", "\\fallingdotseq", "下降点等号", "Falling dotted equals", "relation", 66],
  ["risingdotseq", "\\risingdotseq", "上升点等号", "Rising dotted equals", "relation", 66],
  ["eqcirc", "\\eqcirc", "圆圈等号", "Equal circle", "relation", 68],
  ["circeq", "\\circeq", "等号圆圈", "Circle equal", "relation", 68],
  ["bumpeq", "\\bumpeq", "弧形等号", "Bump equals", "relation", 66],
  ["Bumpeq", "\\Bumpeq", "双弧形等号", "Double bump equals", "relation", 66],
  ["between", "\\between", "介于", "Between", "relation", 64],
  ["pitchfork", "\\pitchfork", "横叉关系", "Pitchfork", "relation", 64],
  ["therefore", "\\therefore", "所以", "Therefore", "relation", 76],
  ["because", "\\because", "因为", "Because", "relation", 76],
  ["plus", "+", "加号", "Plus", "relation", 100],
  ["minus", "-", "减号", "Minus", "relation", 100],
  ["colonop", ":", "冒号", "Colon", "relation", 78],
  ["ldots", "\\ldots", "底部省略号", "Low dots", "relation", 74],
  ["cdots", "\\cdots", "居中省略号", "Centered dots", "relation", 76],
  ["vdots", "\\vdots", "竖向省略号", "Vertical dots", "relation", 74],
  ["ddots", "\\ddots", "右下对角省略号", "Diagonal dots", "relation", 74],
  ["nless", "\\nless", "不小于", "Not less than", "relation", 72],
  ["ngtr", "\\ngtr", "不大于", "Not greater than", "relation", 72],
  ["nleq", "\\nleq", "不小于等于", "Not less or equal", "relation", 72],
  ["ngeq", "\\ngeq", "不大于等于", "Not greater or equal", "relation", 72],
  ["leqslant", "\\leqslant", "斜体小于等于", "Slanted less or equal", "relation", 76],
  ["geqslant", "\\geqslant", "斜体大于等于", "Slanted greater or equal", "relation", 76],
  ["lessdot", "\\lessdot", "点式小于", "Less with dot", "relation", 66],
  ["gtrdot", "\\gtrdot", "点式大于", "Greater with dot", "relation", 66],
  ["lessgtr", "\\lessgtr", "小于或大于", "Less or greater", "relation", 68],
  ["gtrless", "\\gtrless", "大于或小于", "Greater or less", "relation", 68],
  ["lesseqgtr", "\\lesseqgtr", "小于等于或大于", "Less-equal or greater", "relation", 66],
  ["gtreqless", "\\gtreqless", "大于等于或小于", "Greater-equal or less", "relation", 66],
  ["triangleleft", "\\triangleleft", "左三角关系", "Triangle left", "relation", 72],
  ["triangleright", "\\triangleright", "右三角关系", "Triangle right", "relation", 72],
  ["trianglelefteq", "\\trianglelefteq", "左三角或等于", "Triangle left or equal", "relation", 70],
  ["trianglerighteq", "\\trianglerighteq", "右三角或等于", "Triangle right or equal", "relation", 70],
  ["vartriangleleft", "\\vartriangleleft", "变体左三角", "Variant triangle left", "relation", 68],
  ["vartriangleright", "\\vartriangleright", "变体右三角", "Variant triangle right", "relation", 68],
  ["ntriangleleft", "\\ntriangleleft", "非左三角", "Not triangle left", "relation", 64],
  ["ntriangleright", "\\ntriangleright", "非右三角", "Not triangle right", "relation", 64],
  ["ntrianglelefteq", "\\ntrianglelefteq", "非左三角或等于", "Not triangle left or equal", "relation", 62],
  ["ntrianglerighteq", "\\ntrianglerighteq", "非右三角或等于", "Not triangle right or equal", "relation", 62],
  ["square-symbol", "\\square", "空心方形", "Square", "relation", 70],
  ["blacksquare-symbol", "\\blacksquare", "实心方形", "Black square", "relation", 68],
  ["lozenge-symbol", "\\lozenge", "空心菱形", "Lozenge", "relation", 70],
  ["blacklozenge-symbol", "\\blacklozenge", "实心菱形", "Black lozenge", "relation", 68],
  ["bigcirc-symbol", "\\bigcirc", "大空心圆", "Big circle", "relation", 70],
  ["blacktriangle-symbol", "\\blacktriangle", "实心上三角", "Black triangle", "relation", 66],
  ["blacktriangledown-symbol", "\\blacktriangledown", "实心下三角", "Black triangle down", "relation", 66],
  ["blacktriangleleft-symbol", "\\blacktriangleleft", "实心左三角", "Black triangle left", "relation", 66],
  ["blacktriangleright-symbol", "\\blacktriangleright", "实心右三角", "Black triangle right", "relation", 66],

  // 集合与逻辑
  ["subseteq", "\\subseteq", "子集或相等", "Subset or equal", "set", 88],
  ["supset", "\\supset", "真超集", "Superset", "set", 86],
  ["supseteq", "\\supseteq", "超集或相等", "Superset or equal", "set", 84],
  ["sqsubset", "\\sqsubset", "方形真子集", "Square subset", "set", 76],
  ["sqsupset", "\\sqsupset", "方形真超集", "Square superset", "set", 76],
  ["sqsubseteq", "\\sqsubseteq", "方形子集或等于", "Square subset or equal", "set", 78],
  ["sqsupseteq", "\\sqsupseteq", "方形超集或等于", "Square superset or equal", "set", 78],
  ["Subset", "\\Subset", "双线真子集", "Double subset", "set", 72],
  ["Supset", "\\Supset", "双线真超集", "Double superset", "set", 72],
  ["subseteqq", "\\subseteqq", "双线子集或等于", "Double subset or equal", "set", 74],
  ["supseteqq", "\\supseteqq", "双线超集或等于", "Double superset or equal", "set", 74],
  ["nsubseteq", "\\nsubseteq", "不是子集或等于", "Not subset or equal", "set", 70],
  ["nsupseteq", "\\nsupseteq", "不是超集或等于", "Not superset or equal", "set", 70],
  ["ni", "\\ni", "反向属于", "Contains as member", "set", 90],
  ["notni", "\\not\\ni", "不反向属于", "Does not contain as member", "set", 74],
  ["smallsetminus", "\\smallsetminus", "小差集", "Small set difference", "set", 76],
  ["emptyset", "\\emptyset", "空集", "Empty set", "set", 90],
  ["setminus", "\\setminus", "差集", "Set difference", "set", 82],
  ["land", "\\land", "逻辑与", "Logical and", "set", 86],
  ["lor", "\\lor", "逻辑或", "Logical or", "set", 86],
  ["neg", "\\neg", "逻辑非", "Logical not", "set", 84],
  ["Nset", "\\mathbb{N}", "自然数集", "Natural numbers", "set", 88],
  ["Zset", "\\mathbb{Z}", "整数集", "Integers", "set", 88],
  ["Qset", "\\mathbb{Q}", "有理数集", "Rationals", "set", 86],
  ["Rset", "\\mathbb{R}", "实数集", "Real numbers", "set", 92],
  ["Cset", "\\mathbb{C}", "复数集", "Complex numbers", "set", 90],

  // 箭头
  ["uparrow", "\\uparrow", "上箭头", "Up arrow", "arrow", 84],
  ["downarrow", "\\downarrow", "下箭头", "Down arrow", "arrow", 84],
  ["updownarrow", "\\updownarrow", "上下箭头", "Up-down arrow", "arrow", 76],
  ["Leftarrow", "\\Leftarrow", "左双线箭头", "Left double arrow", "arrow", 82],
  ["Leftrightarrow", "\\Leftrightarrow", "等价箭头", "If and only if", "arrow", 88],
  ["mapsto", "\\mapsto", "映射到", "Maps to", "arrow", 86],
  ["longrightarrow", "\\longrightarrow", "长右箭头", "Long right arrow", "arrow", 78],
  ["longleftarrow", "\\longleftarrow", "长左箭头", "Long left arrow", "arrow", 76],
  ["hookrightarrow", "\\hookrightarrow", "右钩箭头", "Right hook arrow", "arrow", 72],
  ["rightharpoonup", "\\rightharpoonup", "右鱼叉箭头", "Right harpoon", "arrow", 70],
  ["leftharpoonup", "\\leftharpoonup", "左鱼叉箭头", "Left harpoon", "arrow", 70],
  ["rightleftarrows", "\\rightleftarrows", "可逆反应箭头", "Equilibrium arrows", "arrow", 78],
  ["longleftrightarrow", "\\longleftrightarrow", "长双向箭头", "Long left-right arrow", "arrow", 78],
  ["Longrightarrow", "\\Longrightarrow", "长右双线箭头", "Long right double arrow", "arrow", 82],
  ["Longleftarrow", "\\Longleftarrow", "长左双线箭头", "Long left double arrow", "arrow", 80],
  ["Longleftrightarrow", "\\Longleftrightarrow", "长等价箭头", "Long equivalence arrow", "arrow", 84],
  ["longmapsto", "\\longmapsto", "长映射箭头", "Long maps-to arrow", "arrow", 76],
  ["hookleftarrow", "\\hookleftarrow", "左钩箭头", "Left hook arrow", "arrow", 72],
  ["rightharpoondown", "\\rightharpoondown", "右下鱼叉箭头", "Right harpoon down", "arrow", 69],
  ["leftharpoondown", "\\leftharpoondown", "左下鱼叉箭头", "Left harpoon down", "arrow", 69],
  ["rightleftharpoons", "\\rightleftharpoons", "右左鱼叉对", "Right-left harpoons", "arrow", 79],
  ["leftrightharpoons", "\\leftrightharpoons", "左右鱼叉对", "Left-right harpoons", "arrow", 77],
  ["nearrow", "\\nearrow", "右上箭头", "North-east arrow", "arrow", 68],
  ["nwarrow", "\\nwarrow", "左上箭头", "North-west arrow", "arrow", 68],
  ["searrow", "\\searrow", "右下箭头", "South-east arrow", "arrow", 68],
  ["swarrow", "\\swarrow", "左下箭头", "South-west arrow", "arrow", 68],
  ["circlearrowright", "\\circlearrowright", "顺时针循环箭头", "Clockwise circular arrow", "arrow", 66],
  ["circlearrowleft", "\\circlearrowleft", "逆时针循环箭头", "Counterclockwise circular arrow", "arrow", 66],
  ["rightsquigarrow", "\\rightsquigarrow", "波浪右箭头", "Squiggly right arrow", "arrow", 70],
  ["twoheadrightarrow", "\\twoheadrightarrow", "双头右箭头", "Two-headed right arrow", "arrow", 70],
  ["twoheadleftarrow", "\\twoheadleftarrow", "双头左箭头", "Two-headed left arrow", "arrow", 70],
  ["Uparrow", "\\Uparrow", "上双线箭头", "Up double arrow", "arrow", 78],
  ["Downarrow", "\\Downarrow", "下双线箭头", "Down double arrow", "arrow", 78],
  ["Updownarrow", "\\Updownarrow", "上下双线箭头", "Up-down double arrow", "arrow", 76],
  ["upuparrows", "\\upuparrows", "双上箭头", "Paired up arrows", "arrow", 70],
  ["downdownarrows", "\\downdownarrows", "双下箭头", "Paired down arrows", "arrow", 70],
  ["leftleftarrows", "\\leftleftarrows", "双左箭头", "Paired left arrows", "arrow", 72],
  ["rightrightarrows", "\\rightrightarrows", "双右箭头", "Paired right arrows", "arrow", 72],
  ["leftrightarrows", "\\leftrightarrows", "左右并列箭头", "Left-right paired arrows", "arrow", 74],
  ["Lleftarrow", "\\Lleftarrow", "左三线箭头", "Triple left arrow", "arrow", 66],
  ["Rrightarrow", "\\Rrightarrow", "右三线箭头", "Triple right arrow", "arrow", 66],
  ["leftarrowtail", "\\leftarrowtail", "左尾箭头", "Left arrow with tail", "arrow", 68],
  ["rightarrowtail", "\\rightarrowtail", "右尾箭头", "Right arrow with tail", "arrow", 68],
  ["looparrowleft", "\\looparrowleft", "左环形箭头", "Left loop arrow", "arrow", 66],
  ["looparrowright", "\\looparrowright", "右环形箭头", "Right loop arrow", "arrow", 66],
  ["curvearrowleft", "\\curvearrowleft", "左弯曲箭头", "Left curved arrow", "arrow", 66],
  ["curvearrowright", "\\curvearrowright", "右弯曲箭头", "Right curved arrow", "arrow", 66],
  ["leftrightsquigarrow", "\\leftrightsquigarrow", "双向波浪箭头", "Left-right squiggle arrow", "arrow", 68],
  ["dashleftarrow", "\\dashleftarrow", "左虚线箭头", "Dashed left arrow", "arrow", 64],
  ["dashrightarrow", "\\dashrightarrow", "右虚线箭头", "Dashed right arrow", "arrow", 64],
  ["Lsh", "\\Lsh", "左折箭头", "Left shift arrow", "arrow", 64],
  ["Rsh", "\\Rsh", "右折箭头", "Right shift arrow", "arrow", 64],
  ["multimap", "\\multimap", "线性映射箭头", "Multimap", "arrow", 72],
  ["nleftarrow", "\\nleftarrow", "非左箭头", "Not left arrow", "arrow", 62],
  ["nrightarrow", "\\nrightarrow", "非右箭头", "Not right arrow", "arrow", 62],
  ["nleftrightarrow", "\\nleftrightarrow", "非双向箭头", "Not left-right arrow", "arrow", 62],
  ["nLeftarrow", "\\nLeftarrow", "非左双线箭头", "Not left double arrow", "arrow", 60],
  ["nRightarrow", "\\nRightarrow", "非右双线箭头", "Not right double arrow", "arrow", 60],
  ["nLeftrightarrow", "\\nLeftrightarrow", "非等价箭头", "Not equivalence arrow", "arrow", 60],
  ["upharpoonleft", "\\upharpoonleft", "向上左鱼叉", "Up harpoon left", "arrow", 64],
  ["upharpoonright", "\\upharpoonright", "向上右鱼叉", "Up harpoon right", "arrow", 64],
  ["downharpoonleft", "\\downharpoonleft", "向下左鱼叉", "Down harpoon left", "arrow", 64],
  ["downharpoonright", "\\downharpoonright", "向下右鱼叉", "Down harpoon right", "arrow", 64],
  ["mapsfrom", "↤", "映射自", "Maps from", "arrow", 72],
  ["longmapsfrom", "⟻", "长映射自", "Long maps from", "arrow", 68],
  ["leadsto", "\\leadsto", "引导箭头", "Leads to", "arrow", 68],

  // 物理常用
  ["planck", "h", "普朗克常数", "Planck constant", "physics", 88],
  ["kb", "k_{\\mathrm{B}}", "玻尔兹曼常数", "Boltzmann constant", "physics", 91],
  ["epsilon0", "\\varepsilon_{0}", "真空介电常数", "Vacuum permittivity", "physics", 89],
  ["mu0", "\\mu_{0}", "真空磁导率", "Vacuum permeability", "physics", 89],
  ["lightspeed", "c", "光速", "Speed of light", "physics", 86],
  ["electroncharge", "e", "元电荷", "Elementary charge", "physics", 84],
  ["laplacian", "\\nabla^{2}", "拉普拉斯算子", "Laplacian", "physics", 88],
  ["divergence", "\\nabla\\cdot", "散度", "Divergence", "physics", 86],
  ["curl", "\\nabla\\times", "旋度", "Curl", "physics", 86],
  ["dagger", "\\dagger", "厄米共轭符号", "Dagger", "physics", 84],
  ["ddagger", "\\ddagger", "双剑号", "Double dagger", "physics", 72],
  ["tensorproduct", "\\otimes", "张量积", "Tensor product", "physics", 88],
  ["directsum", "\\oplus", "直和", "Direct sum", "physics", 82],
  ["hamiltonian-operator", "\\hat{H}", "哈密顿算符", "Hamiltonian operator", "physics", 92],
  ["momentum-operator", "\\hat{\\mathbf{p}}", "动量算符", "Momentum operator", "physics", 90],
  ["angular-momentum-operator", "\\hat{\\mathbf{L}}", "角动量算符", "Angular momentum operator", "physics", 88],
  ["spin-operator", "\\hat{\\mathbf{S}}", "自旋算符", "Spin operator", "physics", 87],
  ["electric-field", "\\mathbf{E}", "电场矢量", "Electric field", "physics", 88],
  ["magnetic-field", "\\mathbf{B}", "磁感应强度", "Magnetic field", "physics", 88],
  ["electric-displacement", "\\mathbf{D}", "电位移矢量", "Electric displacement", "physics", 80],
  ["magnetic-intensity", "\\mathbf{H}", "磁场强度", "Magnetic field intensity", "physics", 80],
  ["current-density", "\\mathbf{J}", "电流密度", "Current density", "physics", 82],
  ["kronecker-delta", "\\delta_{ij}", "克罗内克符号", "Kronecker delta", "physics", 84],
  ["levi-civita", "\\varepsilon_{ijk}", "列维-奇维塔符号", "Levi-Civita symbol", "physics", 82],
  ["four-gradient", "\\partial_{\\mu}", "四维偏导", "Four-gradient", "physics", 81],
  ["metric-tensor", "g_{\\mu\\nu}", "度规张量", "Metric tensor", "physics", 81],
  ["dalembertian", "\\Box", "达朗贝尔算符", "D'Alembert operator", "physics", 80],
  ["imaginary-unit", "\\mathrm{i}", "虚数单位", "Imaginary unit", "physics", 76],
  ["euler-number", "\\mathrm{e}", "自然常数", "Euler's number", "physics", 76],
  ["reduced-compton", "\\ell", "手写小写椭圆符号", "Script ell", "physics", 68],
  ["pauli-vector", "\\boldsymbol{\\sigma}", "泡利矩阵矢量", "Pauli vector", "physics", 83],
];

const simpleCommands = simpleDefinitions.map(
  ([id, command, labelZh, labelEn, category, priority = 72, aliases = [], keywords = []]) =>
    makeCommand(
      id,
      command,
      command,
      command,
      labelZh,
      labelEn,
      category,
      priority,
      aliases,
      keywords,
    ),
);

export const additionalCommands: LatexCommand[] = [
  ...complexCommands,
  ...simpleCommands,
];
