import type { LatexCommand } from "../types/command";

function command(
  id: string,
  value: string,
  category: LatexCommand["category"],
  labelZh: string,
  labelEn: string,
  priority = 70,
): LatexCommand {
  return {
    id,
    command: value,
    insertTemplate: value,
    previewLatex: value,
    labelZh,
    labelEn,
    aliases: [],
    keywords: [labelZh, labelEn],
    category,
    defaultPriority: priority,
    supportedInMathMode: true,
  };
}

export const latestSharedCommands: LatexCommand[] = [
  command(
    "fint",
    "\\fint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "平均积分",
    "Average integral",
    84,
  ),
  command(
    "dashint",
    "\\dashint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "单划线平均积分",
    "Dashed integral",
    83,
  ),
  command(
    "ddashint",
    "\\ddashint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "双划线平均积分",
    "Double-dashed integral",
    82,
  ),
  command(
    "oiint",
    "\\oiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "闭合二重积分",
    "Closed double integral",
    82,
  ),
  command(
    "oiiint",
    "\\oiiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "闭合三重积分",
    "Closed triple integral",
    81,
  ),
  command(
    "ointctrclockwise",
    "\\ointctrclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "逆时针闭合积分",
    "Counterclockwise contour integral",
    80,
  ),
  command(
    "varointclockwise",
    "\\varointclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "顺时针环路积分",
    "Clockwise contour integral",
    79,
  ),
  command(
    "varointctrclockwise",
    "\\varointctrclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "逆时针环路积分",
    "Counterclockwise variant contour integral",
    79,
  ),
  command(
    "bigcap-limits",
    "\\bigcap_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的大交",
    "Big intersection with limits",
  ),
  command(
    "bigcup-limits",
    "\\bigcup_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的大并",
    "Big union with limits",
  ),
  command(
    "bigsqcup-limits",
    "\\bigsqcup_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的不交并",
    "Disjoint union with limits",
  ),
  command(
    "bigvee-limits",
    "\\bigvee_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的大析取",
    "Big logical OR with limits",
  ),
  command(
    "bigwedge-limits",
    "\\bigwedge_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的大合取",
    "Big logical AND with limits",
  ),
  command(
    "bigodot-limits",
    "\\bigodot_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的大点积",
    "Big odot with limits",
  ),
  command(
    "bigoplus-limits",
    "\\bigoplus_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的直和",
    "Direct sum with limits",
  ),
  command(
    "bigotimes-limits",
    "\\bigotimes_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的张量积",
    "Tensor product with limits",
  ),
  command(
    "biguplus-limits",
    "\\biguplus_{i=1}^{n} \\placeholder{}",
    "calculus",
    "带上下限的多重并",
    "Multiset union with limits",
  ),
  command(
    "cases-three",
    "\\begin{cases}\\placeholder{}\\\\\\placeholder{}\\\\\\placeholder{}\\end{cases}",
    "structure",
    "三行分段函数",
    "Three-row cases",
    76,
  ),
  command(
    "matrix-dots",
    "\\begin{bmatrix}\\placeholder{}&\\cdots&\\placeholder{}\\\\\\vdots&\\ddots&\\vdots\\\\\\placeholder{}&\\cdots&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "省略号矩阵",
    "Matrix with dots",
    75,
  ),
  command(
    "diagonal-matrix",
    "\\begin{bmatrix}\\placeholder{}&0&\\cdots\\\\0&\\placeholder{}&\\ddots\\\\\\vdots&\\ddots&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "对角矩阵",
    "Diagonal matrix",
    76,
  ),
  command(
    "augmented-matrix",
    "\\left[\\begin{array}{cc|c}\\placeholder{}&\\placeholder{}&\\placeholder{}\\\\\\placeholder{}&\\placeholder{}&\\placeholder{}\\end{array}\\right]",
    "matrix",
    "增广矩阵",
    "Augmented matrix",
    74,
  ),
  command(
    "block-matrix",
    "\\begin{bmatrix}\\placeholder{}&\\placeholder{}\\\\\\placeholder{}&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "分块矩阵",
    "Block matrix",
    73,
  ),
];
